### ISSUE TITLE
Shortcut to parse a task

### ISSUE THREAD

**Issue by robinttt333** [jmerle/competitive-companion#102]
Is there some keyboard shortcut to directly parse a task?

**Comment by jmerle** [comment]
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> should work.

**Comment by robinttt333** [comment]
Thanks for the quick response.Can it be changed?

**Comment by jmerle** [comment]
Yes, see [Updating shortcuts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Updating_shortcuts).

**Comment by robinttt333** [comment]
Does chrome have a similar support?

**Comment by jmerle** [comment]
See the last sentence in the paragraph I linked in my previous comment.
