### ISSUE TITLE
Parse Topcoder

### ISSUE THREAD

**Issue by emli** [jmerle/competitive-companion#11]
Hi!

I am using this plugin + clion. You know it's so cool. I can actually parse contest in one click. It will nice if add topcoder too.

**Comment by jmerle** [comment]
Because TopCoder demands you to write your code in pre-defined methods, it does not fit in Competitive Companion's format and will therefore not be added.

**Comment by kmyk** [comment]
Could you reopen this?
As you said, Topcoder demands us to write some methods in some classes, but we can automatically generate templates for such methods. In fact, [Greed](https://github.com/zen0wu/topcoder-greed) did this as a plugin for the old Java Arena.
Also, we have no alternatives to Greed on the new Web Arena yet. So, the parser for Topcoder is valuable.

**Comment by jmerle** [comment]
My stance on this is still the same: even though I know this would be a valuable addition, problems from judges like TopCoder and LeetCode are simply incompatible with the type of problems Competitive Companion supports.
