### ISSUE TITLE
Not parsing AIZU-ONLINE-JUDGE

### ISSUE THREAD

**Issue by mfornet** [jmerle/competitive-companion#112]
CC fails to parse this problem from AIZU: http://judge.u-aizu.ac.jp/onlinejudge/description.jsp?id=CGL_1_A

The console log is:
```
TypeError: Cannot read property 'textContent' of null
    at AizuOnlineJudgeProblemParser.parseNormalCategory (common.js:5456)
    at AizuOnlineJudgeProblemParser.<anonymous> (common.js:5444)
    at Generator.next (<anonymous>)
    at common.js:5418
    at new Promise (<anonymous>)
    at push.__awaiter (common.js:5414)
    at AizuOnlineJudgeProblemParser.parse (common.js:5435)
    at VM236 content.js:211
    at Generator.next (<anonymous>)
    at VM236 content.js:169
```

I'm using version 2.17.3

Also by default, when clicking on the extension it doesn't recognize which parser to use:

```Competitive Companion could not determine which parser to parse this page with. Please right-click on the plus icon and select the parser to use via the "Parse with" context menu.```

I selected manually `AizuOnlineJudgeProblemParser` and then got the described error.

**Comment by jmerle** [comment]
The Aizu Online Judge parser in 2.17.3 only supports the beta version of Aizu. I have added a parser for the non-beta version in c4348bff95e34ffb2ba8b0d7a73bb524b35ec686 which will go live somewhere next week.
