### ISSUE TITLE
Hackerrank: grouping problems by contest rather then by primary_contest

### ISSUE THREAD

**Issue by fcottet** [jmerle/competitive-companion#118]
In Hackerrank, you can create contest by selecting different problems from the existing public library.
https://help.hackerrank.com/hc/en-us/articles/115011932508-Contest-overview-and-contest-creation

The contest parser is ignoring the name of the current contest to group the problem based on the primary_contest. So for a **single contest** you end with the following folder structure (using acmX and vscode)
`
{acmx_home}/solutions/HackerRank - World CodeSprint 9/Grading Students
{acmx_home}/solutions/HackerRank - World CodeSprint #4/Gridland Provinces
{acmx_home}/solutions/HackerRank - Week of Code 29/Almost Integer Rock Garden
{acmx_home}/solutions/HackerRank - Week of Code - 20/Non-Divisible Subset
`

It might be easier to group based on the current contest name, e.g. "MyCurrentContest"
`
{acmx_home}/solutions/HackerRank - MyCurrentContest/Grading Students
{acmx_home}/solutions/HackerRank - MyCurrentContest/Gridland Provinces
{acmx_home}/solutions/HackerRank - MyCurrentContest/Almost Integer Rock Garden
{acmx_home}/solutions/HackerRank - MyCurrentContest/Non-Divisible Subset
`

**Comment by jmerle** [comment]
Fixed by #119.
