### ISSUE TITLE
Russian Competitive Programming sites

### ISSUE THREAD

**Issue by emli** [jmerle/competitive-companion#12]
acmp.ru
https://informatics.msk.ru/

It would be nice if you add this sites too

**Comment by jmerle** [comment]
Implemented in 423a506d3ea52c5a2cffcbf90b8ac8a0071d0fc5. I have just published it to the Chrome Web Store and Mozilla's AMO, so it should be available in a few hours. Depending on your browser it can take up to 24 hours before the extension automatically updates.
