### ISSUE TITLE
Parser for other platforms

### ISSUE THREAD

**Issue by saiprasadnayak6858** [jmerle/competitive-companion#120]
I know this tool has a huge library of question parsers but there are some coding sites that I practice on which are not supported like [leetocode](https://leetcode.com), [binarysearch.com](https://binarysearch.com) etc. Can you help me by adding them or guiding me how to add them? :+1:

**Comment by jmerle** [comment]
The websites you listed both require you to write your code in pre-defined methods, which is currently incompatible with Competitive Companion.

**Comment by saiprasadnayak6858** [comment]
Ok thanks :+1:
