### ISSUE TITLE
[Request] add Advent of code

### ISSUE THREAD

**Issue by rishabhdeepsingh** [jmerle/competitive-companion#124]
https://adventofcode.com/2020/day/1

can we add "advent of code" as well to parse problems?

**Comment by Vashi1** [comment]
Uhh.. Well all the inputs for the different problems are different so I think making a parser for that would be difficult.

**Comment by jmerle** [comment]
Competitive Companion only supports sample cases with known input and output, so an Advent of Code parser would only parse the title of the problem. I consider this to be too far of a reach from this project's scope, so I won't add a parser for it.
