### ISSUE TITLE
Vjudge parsing not working properly

### ISSUE THREAD

**Issue by Saurav-Paul** [jmerle/competitive-companion#127]
After parsing one problem from vjudge, if i open next problem to parse, it gives testcases from previous problem.. Please fix it.

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/ede8f54b9ad57ce74b8234829709004bc91565aa, released in 2.19.2. Thanks for reporting the bug!

**Comment by Saurav-Paul** [comment]
@jmerle Thank you for fast response.
