### ISSUE TITLE
UVA external support

### ISSUE THREAD

**Issue by DT3264** [jmerle/competitive-companion#128]
There are direct links to the pdfs, ex. _https://onlinejudge.org/external/115/11518.pdf_ that cannot be parsed unless the problem is seen from the problem's page, ex. _https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&category=24&page=show_problem&problem=2513_, this one is parsed

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/d25749c836b7b999bff8bed014d58b4afc726e90, will be released later today. Note that it will only work on Chrome because Firefox does not allow extensions to run code on tabs displaying PDF files. Thanks for reporting the issue!
