### ISSUE TITLE
USACO Problem Parser broken on non-file IO

### ISSUE THREAD

**Issue by ecnerwala** [jmerle/competitive-companion#129]
USACO recently switched from file I/O to stdin/stdout for the december 2020 contest. This broke the regex which looks for filename.

I don't currently have a link to a problem with the new formatting (they'll be posted soon), but I'm not sure the new formatting will necessarily even be totally consistent going forwards.

**Comment by jmerle** [comment]
I'll wait a few days for the contest to be posted. If it isn't posted before January 8th I'll release a version which will set input/output to stdin/stdout if a filename is not specified to hopefully make sure a working version of the extension is available for the January 2021 contest.

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/079da6c9a508b85f3afd99abb45432c131516985, released in 2.19.4.
