### ISSUE TITLE
Unable to parse test cases from codeforces website 

### ISSUE THREAD

**Issue by biley02** [jmerle/competitive-companion#130]
![Screenshot (480)](https://user-images.githubusercontent.com/57981298/103095896-3367aa00-4628-11eb-8a92-6cf823a73a39.png)
![Screenshot (479)](https://user-images.githubusercontent.com/57981298/103095903-38c4f480-4628-11eb-9875-be445f4d54e7.png)

Please help me resolve this issue.

**Comment by jmerle** [comment]
I cannot reproduce this issue on the same Codeforces problem. Are you perhaps running any Codeforces-specific extensions/userscripts apart from Competitive Companion? It seems like something is adding `<br style="user-select: auto;">` elements to your testcases.

**Comment by biley02** [comment]
Yes, I am using CF-Predictor extension
![Screenshot (482)](https://user-images.githubusercontent.com/57981298/103098248-16cf7000-4630-11eb-8c4e-fc8682f72ac9.png)

**Comment by jmerle** [comment]
The conflicting extension appears to be "[#1 Web & PDF Highlighter - LINER](https://chrome.google.com/webstore/detail/1-web-pdf-highlighter-lin/bmhcbmnbenmcecpmpepghooflbehcack)", which for some reason adds these elements everywhere on the page, including the code blocks containing the testcases. If you uninstall this extension or disable it on `chrome://extensions` it should work again.

**Comment by biley02** [comment]
Wow, its working now. Thanks a lot for help. I could never figure it out myself....Thanks once again.
