### ISSUE TITLE
Failing to parse some of the problems

### ISSUE THREAD

**Issue by DhruvGheewala** [jmerle/competitive-companion#131]
- I face an issue sometimes, in some of the questions, the parser isn't giving correct test cases.
- For exp: You can check this problem: [LASTDIG](https://www.spoj.com/problems/LASTDIG/), [LOCKER](https://www.spoj.com/problems/LOCKER/).
- Screenshot of response: [link](https://ibb.co/M2Pr53w)
- I have faced the same issue on some of the problems from CodeChef, Spoj, and atcoder.

**Comment by jmerle** [comment]
Thanks! I have fixed the issue for the two linked SPOJ problems in https://github.com/jmerle/competitive-companion/commit/3353874cbdddd1dd76ba650cf0577897c70e6e3c. Do you happen to have any links of CodeChef problems and AtCoder problems which the extension is unable to parse correctly?

**Comment by DhruvGheewala** [comment]
@jmerle, I don't remember the problems. but I faced a similar issue on some problems from CodeChef & AtCoder.
how can I adapt this update? Because still, I am getting incorrect test cases. (do I have to reinstall the extension or anything else??)

**Comment by jmerle** [comment]
I have just released version 2.19.5 which contains the fix. It has already been approved on the Mozilla Add-on Store, but is still pending review on the Chrome Web Store. Given the time of year it may take a bit longer for the Chrome extension to be reviewed, but usually it happens within a few days. After it's reviewed your browser will update the extension automatically.

As for CodeChef and AtCoder, please open a new issue if you find other problems which aren't being parsed correctly.

**Comment by jmerle** [comment]
Update: I just noticed the update has already been reviewed and published on the Chrome Web Store, so you should have the update within a day (depending on when the browser decides to check for extension updates). You can also reinstall the extension if you want to update manually.
