### ISSUE TITLE
Parsing Issue

### ISSUE THREAD

**Issue by DhruvGheewala** [jmerle/competitive-companion#138]
The parser fails to parse the below question's input & output.
Problem [link](https://www.codechef.com/problems/FCTRL2/).

Sample Inputs of the problem is [here](https://ibb.co/j8XNqLC).
The response sent from the parser is [here](https://ibb.co/56DY9Qr). <hr>

I found another problem in which the parser is failing to parse test cases.
Problem [link](https://www.spoj.com/problems/ASSIGN/).

**Comment by jmerle** [comment]
Thanks! I have updated the SPOJ and the CodeChef parser so that both problems you linked get parsed correctly. I'll release those updates later this weekend.
