### ISSUE TITLE
Problem parser for Hackerearth practice problems is not working. 

### ISSUE THREAD

**Issue by bipulkmr-crypto** [jmerle/competitive-companion#140]
It is showing some errors and asking me to open browser console. Please look into the matter , I am attaching the error message. I using Mozilla Firefox as my browser and VS code and the extension Competitive Programming helper as an extension.
![image](https://user-images.githubusercontent.com/72005385/109017925-a56a7700-76dd-11eb-8852-e184a087e00a.png)

**Comment by jmerle** [comment]
Fixed in 2.19.9, thanks for reporting the issue.
