### ISSUE TITLE
Add Number of problems in json

### ISSUE THREAD

**Issue by searleser97** [jmerle/competitive-companion#141]
Right now if we clone a contest, it just sends problem by problem individually, so, servers don't know how many problems to expect.

For now, work arounds involve assuming that the time between receiving the i-th problem and the (i+1)-th problem will be less than a second or some small amount of time. (If server didn't receive anything in that time, then shutdown the server). Another thing to notice here is that in Windows it takes a lot of time to send each problem (about 10 seconds each). Other option is to leave the server always running, however, this last option is not always desired.

It would be really nice to know how many problems to expect instead of relying in heuristics.

A simple solution would be to add the total number of problems to the data of each problem, (or probably just to the one that will be sent first), then the servers could read the first Json and extract the total number of problems and just wait until it has received the data for all problems.

When cloning a single problem this value could be just 1, and this would be really helpful to keep consistency in code.

**Comment by jmerle** [comment]
Sorry for the delay, I'm a bit busy nowadays, I'll try to have this feature implemented by the end of the week. Your simple solution sounds like a good one, but I want to spend some days on thinking about possible alternatives and pros/cons before I extend the output format.

**Comment by jmerle** [comment]
I have extended the output format with a batch id and size in 1f59f562135a6875c338e297a49165bea20bc0ad. This is a slightly more advanced version of your simple solution, although you could still use it the same way if you ignore the id (which is fine in most cases).

The reason for there being a batch id is that it is technically possible to parse two or more contests at the same time. Even though I doubt someone ever does that, if it happens you need the batch id to be able to determine which problems belong to which contest.

These changes to the output format are [documented in the README](https://github.com/jmerle/competitive-companion#the-format) and will go live within an hour.
