### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by ffao** [jmerle/competitive-companion#144]
https://github.com/jmerle/competitive-companion/blob/a07e8e5fbb3ec4908e00ba7934fbe7df7441c0ab/src/hosts/CustomHost.ts#L12

Using acmX in my computer the connection takes longer than 500ms, so when I click the "+" button, nothing happens (I know this is the reason because if I fork the extension and change this line to 10000, it works). Would be good if I could increase this value without having to rebuild the extension.

**Comment by jmerle** [comment]
Added in 2cbc3cf21c8cb782ffd92a9d0bb914a1c25bd3c7, will be released soon.
