### ISSUE TITLE
Codeforces contest parse  doesn't working

### ISSUE THREAD

**Issue by emli** [jmerle/competitive-companion#15]
Please see https://github.com/AlexeyDmitriev/JHelper/issues/101

**Comment by jmerle** [comment]
I will take a look at it tonight after work.

**Comment by emli** [comment]
@jmerle are tests parsed also?

**Comment by emli** [comment]
Now it parses correctly. Your minor issue fixed this. @AlexeyDmitriev can you please confirm this too?

**Comment by AlexeyDmitriev** [comment]
So I've tried once now and it worked so probably it got fixed(or it just happen not every time)

**Comment by jmerle** [comment]
Great. If it happens again, please open a new issue. I will publish the changes made in the past few days in a few hours.
