### ISSUE TITLE
Support parsing CodeDrills problems and contests

### ISSUE THREAD

**Issue by Balajiganapathi** [jmerle/competitive-companion#153]
[CodeDrills](https://codedrills.io) is a new competitive coding and interview preparation platform. We are hosting Amritapuri ICPC regionals this year. We will be grateful if you can add support for adding problems and contest parsing support.

Example problem page - https://codedrills.io/problems/tree-parenthesis
Example contest page - https://codedrills.io/contests/amrita-icpc-practice-session-4
Contests page - https://codedrills.io/contests

Let me know if any more information is required.

**Comment by jmerle** [comment]
Thanks for the feature request, I have added a problem parser for CodeDrills in 2.22.0. I won't be adding a contest parser because CodeDrills loads problems dynamically using a gRPC API, which the extension cannot make calls to.
