### ISSUE TITLE
[Feature Request] Parse via Right-click Menu

### ISSUE THREAD

**Issue by Hikarii0703** [jmerle/competitive-companion#154]
This extension has been very useful so far, but there's one thing I don't like about it. Everytime a user wants to parse something, they have to click on the green button next to the URL bar. I suggest adding another button on the right-click menu, so that there's no need to move the cursor all the way up, just right-click and it will work.

**Comment by jmerle** [comment]
I understand the problem, but I don't think a context menu entry is the solution. At the moment the fastest way to parse a problem is using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> keyboard shortcut, and a context menu entry isn't going to improve upon that. On top of that I don't think Competitive Companion is an extension that should nest itself into the context menu of every page, so I'm going to say no to this feature request.
