### ISSUE TITLE
Redundant test cases when pasering a problem from acwing.com

### ISSUE THREAD

**Issue by tw-luo** [jmerle/competitive-companion#161]
If there is a `code` tag(if markdown is used)  in the input format and output format , it will also be recognized as a test case.

For example, this problem: https://www.acwing.com/problem/content/3492/

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/93c710aecf739798d187785049e58a8ae28215a8, released in 2.25.1. Thanks for reporting the issue!

**Comment by tw-luo** [comment]
> Fixed in [93c710a](https://github.com/jmerle/competitive-companion/commit/93c710aecf739798d187785049e58a8ae28215a8), released in 2.25.1. Thanks for reporting the issue!
Thanks

**Comment by tw-luo** [comment]
Thanks
