### ISSUE TITLE
CODEFORCES PROBLEM GROUPER

### ISSUE THREAD

**Issue by ishika261** [jmerle/competitive-companion#163]
Nothing can be done if we want to make code files for each problem in the contest, and also how to change the name of the code file saved on vs code? if instead of the problem name we want problem no. as the code file name/?

**Comment by jmerle** [comment]
Sorry for the late reply. Competitive Companion only parses problems and sends the extracted data to external tools like CHelper, JHelper, Hightail, acmX and others. Those external tools are not made by me, you should send this suggestion to the developer(s) of the tool that you are using.
