### ISSUE TITLE
TypeError: Cannot read property 'textContent' of undefined

### ISSUE THREAD

**Issue by w93163red** [jmerle/competitive-companion#169]
The problem link: https://codeforces.com/problemset/problem/1220/C

when clicked the extension, it shows:
```
 TypeError: Cannot read property 'textContent' of undefined
    at CodeforcesProblemParser.parseMainProblem (common.js:1)
    at CodeforcesProblemParser.parse (common.js:1)
    at u (content.js:1)
    at content.js:1
u @ content.js:1

```

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/f545d2c09c227cf57ea6709c4910d8cc0146c27d, will go live within an hour. Thanks for reporting the issue!
