### ISSUE TITLE
Can't parse acmp 

### ISSUE THREAD

**Issue by emli** [jmerle/competitive-companion#17]
Can't parse https://acmp.ru/index.asp?main=task&id_task=120 this problem

**Comment by emli** [comment]
@jmerle can we do it? It would be nice if we can do ASAP

**Comment by jmerle** [comment]
Fixed in ed706060f287f3455ff709c406fe8c0d7ad29bd1 which will go live in a minute.

**Comment by emli** [comment]
@jmerle thanks man, very helpful
