### ISSUE TITLE
Parsing a DMOJ problem gives contest in `problem` not `group` 

### ISSUE THREAD

**Issue by p00f** [jmerle/competitive-companion#170]
When I try to parse https://dmoj.ca/problem/canada21p1, I get `group` as "DMOJ" and `problem` as "Canada Day Contest 2021 - Bob and Canada", whereas normally the contest is part of the `group` (ie `group` should be judge + contest)

**Comment by jmerle** [comment]
Thanks for reporting the issue, fixed in https://github.com/jmerle/competitive-companion/commit/6d950461f1e32078ea82c7a84948a6013c3490dd, released in 2.25.5.

**Comment by p00f** [comment]
Thanks!
