### ISSUE TITLE
Grepper extension problem

### ISSUE THREAD

**Issue by anurag3301** [jmerle/competitive-companion#171]
Please check this issue on [p00f/cphelper.nvim](https://github.com/p00f/cphelper.nvim/issues/9)

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/b8af9f57df4b51d6d554acde41043d6497a342e2, released in 2.25.6, see https://github.com/p00f/cphelper.nvim/issues/9#issuecomment-892316852. Thanks for letting me know about the issue in your repository!

**Comment by anurag3301** [comment]
Got it, Thanks for fixing it 😊
