### ISSUE TITLE
Ctrl + Shift + U doesn't work

### ISSUE THREAD

**Issue by tuwuna** [jmerle/competitive-companion#173]
**Browser**
Chrome on Arch Linux

**Workaround**
Change shortcut in `chrome://extensions/shortcuts`

**Request**
Add workaround to extension description because it helps people who didn't know how to manage shortcut (Like me)

**Comment by jmerle** [comment]
I extended the extension descriptions on the Chrome Web Store and Mozilla's AMO to include a short description on how to change the shortcut. The AMO change is already live, the Chrome Web Store change will be visible after the next extension release has been reviewed and published by Google (should be the case within an hour from this comment).
