### ISSUE TITLE
Unable to parse Kattis problem 'backspace'

### ISSUE THREAD

**Issue by pareronia** [jmerle/competitive-companion#175]
See: https://open.kattis.com/problems/backspace

I'm guessing the angle brackets in the test data are screwing up the parsing?

**Comment by jmerle** [comment]
The problem is the missing code block for sample output 3. I fixed the bug in https://github.com/jmerle/competitive-companion/commit/402ded9cd02917b4e1245873d71d3ff384467d1b which will be released within an hour. Thanks for reporting the issue!

**Comment by pareronia** [comment]
Dankjewel, en: graag gedaan ;-)
