### ISSUE TITLE
Is the ouput guaranteed to be in one line?

### ISSUE THREAD

**Issue by p00f** [jmerle/competitive-companion#176]
https://github.com/jmerle/competitive-companion#the-format

When I parse a problem, all the json output is in a single line (ie the last line of the POST request). Can my editor-side tool rely on this behaviour?

**Comment by jmerle** [comment]
It's guaranteed that the entire POST body contains 1 JSON object as described in the readme (that is if you don't listen on port 4243, which receives an extra line for CHelper compatibility). It's not guaranteed that the JSON is sent in a minified manner in a single line, but I haven't had a need to change it from its current behavior in the past 3+ years, so I guess you're fine if you rely on this being the case.

On the other hand, I've never seen a programming language in which parsing a multi-line POST body was a problem, so I fail to see how this would be a concern.

**Comment by p00f** [comment]
Thanks!
