### ISSUE TITLE
Not able to Parse Codechef  contest problems' testcases

### ISSUE THREAD

**Issue by akashbansal-cp** [jmerle/competitive-companion#177]
Now after the latest update, with CodeChef including the copy button on their CodeChef problem page and many more, I think they changed some tags and now the extension is unable to detect test cases,  and only creates an empty folder with name test cases.
The above issue only arises while parsing contests, not individual problems.
For Individual problems, It works fine.

**Comment by jmerle** [comment]
I can't reproduce this on [MAY20B](https://www.codechef.com/MAY20B), [COOK118A](https://www.codechef.com/COOK118A) nor [LTIME84B](https://www.codechef.com/LTIME84B). Please provide a link to a page which the extension is failing on.

**Comment by akashbansal-cp** [comment]
Ongoing Challenge
https://www.codechef.com/AUG21B
Hope, This would help.
![cp](https://user-images.githubusercontent.com/26535857/128667622-21948c95-6932-4754-9121-47f2bc6f3a59.gif)

**Comment by jmerle** [comment]
Not exactly sure why I wasn't able to reproduce this 8 days ago, but I did manage to reproduce it today, fixed it in https://github.com/jmerle/competitive-companion/commit/c72df45379dfd85d9854b48e5fca973833786ce6 and released it in 2.25.8. Thanks for reporting the issue!

**Comment by jmerle** [comment]
Nice catch, fixed in https://github.com/jmerle/competitive-companion/commit/2127317bfaef0f877bd810efe8d1dbba4ba853f1, released in 2.25.9.
