### ISSUE TITLE
[urgent] Not able to parse codedrills.io problems.

### ISSUE THREAD

**Issue by King-01** [jmerle/competitive-companion#179]
It was working fine around 7 days ago, I think the reason its not working now is the recent changelog. I have acm-icpc regionals in 24 hours, so its kind of urgent, please look into it. I am attaching link to the issue as image.
[Link to screenshot showing error with console output](https://imgur.com/a/b8eM6IX)

**Comment by jmerle** [comment]
I'm on vacation at the moment, I won't be able to fix this issue before Monday I'm afraid.

**Comment by King-01** [comment]
Can I do any temprory fixesfor the problem, like using the last version of companion, the one before last commit?

**Comment by jmerle** [comment]
Unfortunately not, the last time the CodeDrills parser got an update was on July 12th, so if it worked last week it's a recent CodeDrills update that broke it, not the last commit to the CodeDrills parser.

What you could do is fork and clone the repository, follow the [Running locally](https://github.com/jmerle/competitive-companion#running-locally) instructions to run your own version of the extension locally, and then fix the parser in [src/parsers/problems/CodeDrillsProblemParser.ts](https://github.com/jmerle/competitive-companion/blob/master/src/parsers/problem/CodeDrillsProblemParser.ts). You can then also create a pull request with your fix to this repository, but I won't be able to test, merge and release your changes to the Chrome Web Store and Mozilla's AMO before I get back home on Monday.

**Comment by King-01** [comment]
Okay, thank you very much

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/ccbd7d77d67a135a053a2c90bcc098bb827e93dc, released in 2.25.8.
