### ISSUE TITLE
Test parsed incorrectly

### ISSUE THREAD

**Issue by emli** [jmerle/competitive-companion#18]
![image](https://user-images.githubusercontent.com/5517490/49987658-460d6a00-ff9e-11e8-8ac5-81c732fb2bb4.png)

http://acmp.ru/index.asp?main=task&id_task=536 

Third test should be

1 8 3
9

**Comment by jmerle** [comment]
Fixed in 48eadbb84f2b58e76185efb48e0fe3bf2498e747 which will go live in about 24 hours since I want to add some other things too.
