### ISSUE TITLE
Suggestion : support for CodeStudio

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [jmerle/competitive-companion#184]
Support for CodeStudio by CodingNInjas can be added.

Link:- https://www.codingninjas.com/codestudio

**Comment by hrishikesh-deshpande** [comment]
Problem link :- https://www.codingninjas.com/codestudio/problems/order-of-people-heights_1170764

**Comment by jmerle** [comment]
It seems like CodeStudio requires code to be written in pre-defined methods, which does not fit in Competitive Companion's format, so a CodeStudio parser won't be added.
