### ISSUE TITLE
Add support for Yandex problem link without problem ID

### ISSUE THREAD

**Issue by user202729** [jmerle/competitive-companion#188]
When "Problems" link on the "top navigation bar" is clicked the URL looks like this

```
https://official.contest.yandex.com/<contest name>/contest/<contest ID>/problems/
```

which is usually equivalent to

```
https://official.contest.yandex.com/<contest name>/contest/<contest ID>/problems/A/
```

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/dc19c8d9813e7d13df9f90fff43ad83b45bd4888, will be released within an hour. Thanks for reporting the issue!
