### ISSUE TITLE
Add support for noj

### ISSUE THREAD

**Issue by Heartfirey** [jmerle/competitive-companion#199]
[NOJ on Github](https://github.com/ZsgsDesign/NOJ)
As the title described, I recommend competitive-companion add support for this online judge call NOJ. Thank you!

**Comment by jmerle** [comment]
Implemented in https://github.com/jmerle/competitive-companion/commit/893b8b8f16d519283188a2a58680b5201972e612, released in 2.29.0, thanks for the feature request.
