### ISSUE TITLE
Red Panda Dev-C++ Support

### ISSUE THREAD

**Issue by royqh1979** [jmerle/competitive-companion#200]
Hi, I'm the author of Red Panda Dev-C++. [https://github.com/royqh1979/RedPanda-CPP](https://github.com/royqh1979/RedPanda-CPP)
I'm planning to add competitive-companion support in the next release.
Can i use 10046 as the default port?

**Comment by royqh1979** [comment]
See. Thanks for the reply.

And what's the text encoding for the json data? Is it always utf-8, or depends on the website? 
If it's the later case, can you add an "encoding" property to the json object posted by the competitive companion?

**Comment by jmerle** [comment]
The encoding should always be UTF-8, if you see it being anything else then that's a bug.

**Comment by royqh1979** [comment]
thanks. I have finished the competitive companion support using port 10045.

**Comment by royqh1979** [comment]
Please add Red-Panda C++ (https://github.com/royqh1979/RedPanda-CPP) to the supported tools

**Comment by jmerle** [comment]
Added in https://github.com/jmerle/competitive-companion/commit/caec3595b3dff8d6227aa069ab648e9da3d5a116.
