### ISSUE TITLE
companion not working with A20j ladders

### ISSUE THREAD

**Issue by cruze0210** [jmerle/competitive-companion#202]
The competitive companion fails to work for A2OJ ladders 
https://a2oj.com/ladders 
 please fix this as soon as possible

**Comment by jmerle** [comment]
I had no idea A2 Online Judge became opened again, thanks for the feature request! Implemented in https://github.com/jmerle/competitive-companion/commit/40a53c974be60b02e311f8967b129baab8b167d1, released in 2.31.0.
