### ISSUE TITLE
Contest name aka group is not parsed for DMOJ

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#205]

**Comment by jmerle** [comment]
Similar to #206, can you please share link to a problem it is failing on? I just tried it on [NOIP '21 P1 - Saying Numbers](https://dmoj.ca/problem/noip21p1) and got the following (correct) output:
```
{
    "name": "P1 - Saying Numbers",
    "group": "DMOJ - NOIP '21",
    "url": "https://dmoj.ca/problem/noip21p1",
    "interactive": false,
    "memoryLimit": 512,
    "timeLimit": 1000,
    "tests": [
        {
            "input": "4\n6\n33\n69\n300\n",
            "output": "8\n36\n80\n-1\n"
        },
        {
            "input": "5\n90\n99\n106\n114\n169\n",
            "output": "92\n100\n109\n-1\n180\n"
        }
    ],
    "testType": "single",
    "input": {
        "type": "stdin"
    },
    "output": {
        "type": "stdout"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "P1SayingNumbers"
        }
    },
    "batch": {
        "id": "d6cf57a3-b5cf-479d-be7e-d3a4d3bad88b",
        "size": 1
    }
}
```

**Comment by EgorKulikov** [comment]
Take for example https://dmoj.ca/problem/coci21c1p1
I've got {"name":"COCI '21 Contest 1 #1 Ljeto","group":"DMOJ","url":"https://dmoj.ca/problem/coci21c1p1","interactive":false,"timeLimit":1000,"tests":[{"input":"3\n10 1 6\n20 1 7\n21 8 1\n","output":"250 100\n"},{"input":"3\n10 2 5\n15 2 6\n25 2 5\n","output":"400 0\n"},{"input":"2\n10 5 2\n11 6 3\n","output":"0 200\n"}],"testType":"single","input":{"type":"stdin","fileName":null,"pattern":null},"output":{"type":"stdout","fileName":null,"pattern":null},"languages":{"java":{"taskClass":"COCI21Contest11Ljeto"}}}

**Comment by jmerle** [comment]
Thanks for this one as well! Fixed in https://github.com/jmerle/competitive-companion/commit/888c7276cd1f307e2d7fbe11f747db10dc6837f8, will go live within 30 minutes.
