### ISSUE TITLE
Task name and class are not parsed for HackerEarth

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#206]

**Comment by jmerle** [comment]
Can you please share a link to a problem it is failing on? I just tried parsing [Maximum Sum](https://www.hackerearth.com/practice/algorithms/searching/linear-search/practice-problems/algorithm/maximum-sum-4-f8d12458/) and got the following (correct) output:
```
{
    "name": "Maximum Sum",
    "group": "HackerEarth - Algorithms - Searching - Linear Search",
    "url": "https://www.hackerearth.com/practice/algorithms/searching/linear-search/practice-problems/algorithm/maximum-sum-4-f8d12458/",
    "interactive": false,
    "memoryLimit": 256,
    "timeLimit": 1000,
    "tests": [
        {
            "input": "5\n1 2 -4 -2 3\n",
            "output": "6 3\n"
        }
    ],
    "testType": "single",
    "input": {
        "type": "stdin"
    },
    "output": {
        "type": "stdout"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "MaximumSum"
        }
    },
    "batch": {
        "id": "e70854dd-ae05-411c-8d62-c339b2921732",
        "size": 1
    }
}
```

**Comment by EgorKulikov** [comment]
For https://www.hackerearth.com/challenges/competitive/december-circuits-21-2/algorithm/path-smallest-63a01482/ I am getting //{"name":"Task","group":"HackerEarth - December Circuits '21","url":"https://www.hackerearth.com/challenges/competitive/december-circuits-21-2/algorithm/path-smallest-63a01482/","interactive":false,"timeLimit":1000,"tests":[{"input":"8 2\n105 2 9 3 8 5 7 7\n1 2\n1 3\n1 4\n3 5\n3 6\n3 7\n4 8\n8 7 5\n8 7 3\n","output":"105 7\n"}],"testType":"single","input":{"type":"stdin","fileName":null,"pattern":null},"output":{"type":"stdout","fileName":null,"pattern":null},"languages":{"java":{"taskClass":"Task"}}}

**Comment by jmerle** [comment]
Thanks! Fixed in https://github.com/jmerle/competitive-companion/commit/65679851fe9a879da3c0c3c46fad43e599e59a5b, will go live within an hour.
