### ISSUE TITLE
Competitive Programming Praser not working

### ISSUE THREAD

**Issue by Shashank2211** [jmerle/competitive-companion#208]
Competitive Companion could not determine which parser to parse this page with. Please right-click on the plus icon and select the parser to use via the "Parse with" context menu. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug.
When done as said, it says "Something went wrong while running Competitive Companion's CodeChefContestParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug."
Error in the console - "Failed to parse any task.
    at CodeChefContestParser.parse (chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/common.js:1)
    at async l (chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/content.js:1)
l @ content.js:1"

**Comment by jmerle** [comment]
Can you please share a link to a contest it is failing on? I just tried parsing [December Lunchtime 2021 Division 1](https://www.codechef.com/LTIME103A) and didn't see any errors.

**Comment by Shashank2211** [comment]
Actually I restarted my browser and apparently it worked and the error was
no longer there.
Thank you for the concern though.
