### ISSUE TITLE
Not working with some problems on codechef

### ISSUE THREAD

**Issue by ujjwalgarg100204** [jmerle/competitive-companion#216]
![image](https://user-images.githubusercontent.com/89966270/148878743-0d4d6c51-3e55-4e63-b96c-4abf84ab53cb.png)

![image](https://user-images.githubusercontent.com/89966270/148878778-8876787c-a6a3-4c80-bf38-09f5aa50ced4.png)

![image](https://user-images.githubusercontent.com/89966270/148878801-ed63a96d-d022-4de5-834a-a4b01c5cbda1.png)

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/66a9c2448432512bf7cf311e64c1c00a3b6ad53e, will be released within 30 minutes. Thanks for reporting the issue!
