### ISSUE TITLE
Not working for Codechef Long Challenge February 15.

### ISSUE THREAD

**Issue by horcrux2301** [jmerle/competitive-companion#22]
I tried parsing the contest  - [Link](https://www.codechef.com/FEB15)
However the parsing failed.

I can see that all the calls to the Codechef API were successful with 200.

Relevant screenshots -

<img width="1316" alt="screen shot 2019-01-10 at 5 52 13 am" src="https://user-images.githubusercontent.com/25867561/50937946-030abd80-149c-11e9-8071-dc2657d5703e.png">

<img width="1059" alt="screen shot 2019-01-10 at 5 52 32 am" src="https://user-images.githubusercontent.com/25867561/50937947-030abd80-149c-11e9-97ed-0e78a62120d0.png">

Edit:- Same case for JULY15 and DEC15 as well.

**Comment by jmerle** [comment]
Thanks for reporting the bug. I'll fix it this weekend.

**Comment by jmerle** [comment]
I released version 2.5.1 which contains the fix for this issue. It can take up to 24 hours for the browser to automatically update the extension.
