### ISSUE TITLE
Change the default class name

### ISSUE THREAD

**Issue by anujpatel224** [jmerle/competitive-companion#229]
Whenever i pass a problem from codechef , it creates the file with name of the problem. for example if the problem name is "Guess the bottom face" it will create the file "Guess_the_bottom_face.java". is it possible to configure it in such a way that it will always create Codechef.java or Codechef.cpp file ?

**Comment by jmerle** [comment]
Competitive Companion only parses problems and sends the extracted data to external tools, which in turn usually create the C++ or Java file you are talking about. Those external tools are not made by me, you should send this question to the developer(s) of the tool that you are using.
