### ISSUE TITLE
key board short cut

### ISSUE THREAD

**Issue by ashiknur** [jmerle/competitive-companion#232]
Please create some short cut key to perse using keyboard short cut.

**Comment by jmerle** [comment]
This feature already exists. The default shortcut is <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd>, which can be changed on `chrome://extensions/shortcuts` when using Chrome and on `about:addons` > Cog > Manage Extension Shortcuts when using Firefox.
