### ISSUE TITLE
CSES parser not automatically detecting CSES problems

### ISSUE THREAD

**Issue by bageljrkhanofemus** [jmerle/competitive-companion#234]
https://www.cses.fi/problemset/task/1712/: example
Whenever it sees a CSES problem it cannot determine which parser to use, but it works perfectly fine with the CSES parser when I select it manually.
Is it possible to default to the CSES parser for that domain?

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/19ba48854ba2fb6b51715aeb9e2636ba0aa7a62a, will be released later this weekend.
