### ISSUE TITLE
Provide support for Newton School website.

### ISSUE THREAD

**Issue by King-01** [jmerle/competitive-companion#235]
This website holds competitive programming contests and their last contest had 12k participants with tourist also participating in it.
Link to leaderboard - https://my.newtonschool.co/course/jtrr9p6u9dat/assignment/rkp1ithkwgfx/dashboard/?tab=leaderboard
It would be really nice if competitive companion provides the support for this website.

**Comment by King-01** [comment]
Link to the page having list of all the contests - https://my.newtonschool.co/contest/all

**Comment by jmerle** [comment]
Added in https://github.com/jmerle/competitive-companion/commit/ff0840456f19834415cc1ed31c445bb09e8cdfed, will be released later today.
