### ISSUE TITLE
Can not use this in geeksforgeeks.com and leetcode.com.

### ISSUE THREAD

**Issue by tonmoy197** [jmerle/competitive-companion#242]

**Comment by krishnakumarg1984** [comment]
Bump this.

**Comment by jmerle** [comment]
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+GeeksforGeeks+OR+Geeks), please see #245 for more information.
