### ISSUE TITLE
Not Working on Codechef new problem page

### ISSUE THREAD

**Issue by jyoti-prakash-25** [jmerle/competitive-companion#246]
![Screenshot (15)](https://user-images.githubusercontent.com/92805753/169751465-0da7d827-254b-4503-b9c0-36bf20388396.png)

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/9695370d46e667245f3f9b68c9ce53e9c8cb8bad, will be released within an hour. Thanks for reporting the issue!
