### ISSUE TITLE
Problem in AtCoder

### ISSUE THREAD

**Issue by jyoti-prakash-25** [jmerle/competitive-companion#247]
In AtCoder while creating the file name it adds a hyphen to it. But hyphen is not supported as a class name so we cannot us it in atcoder.

**Comment by jmerle** [comment]
Competitive Companion only parses problems and sends the extracted data to external tools, which in turn create the file you are talking about. These external tools are not made by me, you should send this issue to the developer(s) of the tool that you are using.
