### ISSUE TITLE
New UI of Kattis not works with Competitive Companion

### ISSUE THREAD

**Issue by aayushbest** [jmerle/competitive-companion#251]
Attaching the screenshot for the better understanding.
website: open.kattis.com
![image](https://user-images.githubusercontent.com/34985919/172171927-1ef9c2c2-ce66-4140-b02a-8f7fcb2b7daa.png)

**Comment by jmerle** [comment]
Fixed in [https://github.com/jmerle/competitive-companion/commit/27d02575bdfd5ad65e5808790051afa78773af06], will be released within an hour. Thanks for reporting the issue!
