### ISSUE TITLE
Competetive Companion's LeetCode parser is not working

### ISSUE THREAD

**Issue by opticSquid** [jmerle/competitive-companion#254]
![image](https://user-images.githubusercontent.com/59192460/174214871-324e1719-e446-4107-94b6-6752a50f43a1.png)

I'm using 
- OS: Ubuntu 22.04
- DE - GNOME
- Display Server- Wayland
- Google Chrome Build- Version 102.0.5005.115

**Comment by jmerle** [comment]
Competitive Companion does not have a LeetCode parser, see #245.
