### ISSUE TITLE
unable to use competitive programming helper extension ... throws a parse error

### ISSUE THREAD

**Issue by cod-er-11** [jmerle/competitive-companion#255]

**Comment by jmerle** [comment]
I cannot fix "throws a parse error" with the limited information you provided. Please provide a link to the problem or contest at which the parse error occurs and a screenshot of the exact error you're seeing.

**Comment by jmerle** [comment]
Thanks! Fixed in e9e6cdc5e91f07c9780aab94a913fcbb6a1d51e2, will be released later today.
