### ISSUE TITLE
CodeForces - only one problem parsed

### ISSUE THREAD

**Issue by SathOkh** [jmerle/competitive-companion#256]
I've tried to parse, e.g. following the contest on code forces: https://codeforces.com/contest/1693, but it seems like only one (last) problem is parsed and sent to the plugin - here example with Competitive Programming Helper on Visual Studio Code:
![image](https://user-images.githubusercontent.com/2511493/175282937-5d6f3950-e9cc-4551-975a-6ffc40243fd0.png)

Is it intended behavior or a bug?

Used version of the plugin:
![image](https://user-images.githubusercontent.com/2511493/175284075-ae5a0327-a70b-4627-adde-5f30f87fc890.png)

**Comment by jmerle** [comment]
I cannot reproduce this issue. Can you please go to the extension's options (right-click on the green plus icon > Options), turn on "Debug mode", and then try to parse the contest again with the browser console open (F12 > Console)? If you do that, do you see 
 see 6 JSON objects, one for each problem (you might have to scroll the console a bit)? Like the ones shown in my console on the right here:
![](https://user-images.githubusercontent.com/14951909/175305234-f9a483fd-28f1-4ba9-9783-fddb010197df.png)
