### ISSUE TITLE
Option to replace characters of problem title and problem group

### ISSUE THREAD

**Issue by mahbd** [jmerle/competitive-companion#258]
It will be nice to have an option to replace characters of title and group name. Such as replace space with underscore.

**Comment by jmerle** [comment]
I understand what you want to do, but this is out-of-scope for Competitive Companion. Competitive Companion's task is to extract the original problem data, post-processing that data is the task of external tools. Post-processing includes all changes made to the data to make it fit your use case, like converting the problem name to be safe to use as file name, changing the formatting of the problem's group property to use it as archive path, and applying user-defined replacements.
