### ISSUE TITLE
Offline distribution of the extension

### ISSUE THREAD

**Issue by AlexeyDmitriev** [jmerle/competitive-companion#26]
Hi, I'd like to use this extension during the contest where I will not have access to the Internet but where I an prepare archive with data

Can you explain how to create extension to Chrome/FF and how to install it offline later?

Thanks.

**Comment by jmerle** [comment]
Sure. First of all, download the extension archive of [the latest release](https://github.com/jmerle/competitive-companion/releases). This is the same archive as the one you download by installing through the Chrome Web Store or Mozilla's AMO. After that the steps differ depending on the browser.

Firefox:
1. Go to `about:addons`
2. Click on the "Extensions" tab on the right
3. Click on the little gear icon in the top right
4. Select "Debug Add-ons"
5. Click on the "Load Temporary Add-on" button
6. Select the archive you just downloaded

Chrome:
1. Extract the contents of the archive you just downloaded to a separate directory
2. Go to `chrome://extensions/`
3. Click on the "Load unpacked" button in the top left
4. Select the directory you just extracted the archive to

On Firefox you'll have to repeat this process every time you restart the browser. On Chrome it will be persistent.
