### ISSUE TITLE
Not working in LightOJ anymore

### ISSUE THREAD

**Issue by DrSwad** [jmerle/competitive-companion#260]
The LightOJ website went through a revamp quite a while ago, which might be the reason the extension isn't working there anymore.

Example problems I tried to parse:

- https://lightoj.com/problem/drunk
- https://lightoj.com/problem/farthest-nodes-in-a-tree

Browser console log:

```
TypeError: Cannot read properties of null (reading 'textContent')
    at LightOJProblemParser.parse (common.js:1:330114)
    at l (content.js:1:320)
    at content.js:1:1220
l @ content.js:1
```

**Comment by jmerle** [comment]
Fixed in 2f7c23be96fb82774d582338b1a44d792fba60e0, will be released within an hour. Thanks for reporting the issue!
