### ISSUE TITLE
Parser not working on codechef practice in self learn 

### ISSUE THREAD

**Issue by devhiteshk** [jmerle/competitive-companion#265]
[www.codechef.com-1658204453282.log](https://github.com/jmerle/competitive-companion/files/9137447/www.codechef.com-1658204453282.log)

**Comment by pawan-nirpal-031** [comment]
Yea bro me too.

**Comment by devhiteshk** [comment]
![Screenshot 2022-07-19 100011](https://user-images.githubusercontent.com/40910893/179664993-3289baee-adea-4aa1-aa62-673606fac0b4.png)
I got the solution but it will only work until they support old problem formats, which they may take down in future.

### **click switch to old problems page and then parse it works**
