### ISSUE TITLE
not able to access contest problem in visual studio code 

### ISSUE THREAD

**Issue by piyushraj6161** [jmerle/competitive-companion#269]
https://www.codechef.com/JULY222D/problems-old/INSURANCE

**Comment by Sanu3007** [comment]
@jmerle  competitive companion does not able pass the contest problem on codechef.
here is the problem link : 
https://www.codechef.com/JULY222D/problems/SUMOFPROD1

Error message : 

content.js:1 TypeError: Cannot read properties of undefined (reading 'textContent')
    at CodeChefOldProblemParser.parse (common.js:1:299224)
    at l (content.js:1:320)
    at content.js:1:1263

**Comment by jmerle** [comment]
There's no need to tag me (@\<username>) in comments on open issues, all it does is generate unnecessary notifications.

I'm currently on vacation without a laptop, so this issue won't be fixed before I return late June 28th. In the mean time you may be able to parse these problems by right-clicking the green plus icon > Parse with > Problem parser > CodeChefNewProblemParser (I think this is what #270 suggests). However, keep in mind that this only works if CodeChef hasn't changed the problem page itself (from what I can see on my phone they only changed the URLs).

**Comment by jmerle** [comment]
This bug is fixed in c4b0a594373a956d2cb03340403da457b3c39464 which will be released within an hour.
