### ISSUE TITLE
CodeChef Contest parser needs an update

### ISSUE THREAD

**Issue by RoyCoding8** [jmerle/competitive-companion#274]
In the last July Long Challenge 2 '22 of CodeChef, th contest parser wasn't working.... Had to select problem parser manually every time.....

(If it has already been fixed, pls let me know I'll close the issue)

**Comment by myselfdeepdas** [comment]
@RoyCoding8 to parse these problems you have to do right-clicking on the green plus icon > Parse with > Problem parser > CodeChefNewProblemParser

**Comment by RoyCoding8** [comment]
@myselfdeepdas Yeah that's what I did but it would be more convenient if the contest parser worked... since that opens by default...

**Comment by jmerle** [comment]
This bug is fixed in c4b0a594373a956d2cb03340403da457b3c39464 which will be released within an hour.

**Comment by RoyCoding8** [comment]
@jmerle Okay thnx :)
