### ISSUE TITLE
Codechef Contest Parser needs to be updated 

### ISSUE THREAD

**Issue by dipanshusingh2107** [jmerle/competitive-companion#276]
https://www.codechef.com/submit/VALIDMIN

Codechef Contest Parser is not working.
Codechef New Problem Parser is working
![Screenshot 2022-07-30 at 11 05 32 AM](https://user-images.githubusercontent.com/47363596/181876373-9e25b805-17ac-4c43-9d86-4e781e5efe93.png)
.

**Comment by vens8** [comment]
yeah, it works when you right click on the icon and go to "parse-with > Problem Parser > CodeChefNewProblemParser"

Detection of old problem vs new problem needs fixing.

**Comment by jmerle** [comment]
Fixed in https://github.com/jmerle/competitive-companion/commit/92e528c204612c393ae6b15443b6400d40a9eaf4, will be released within an hour. Thanks for reporting the issue!
