### ISSUE TITLE
Include Problem Number in Problem Name for CSES

### ISSUE THREAD

**Issue by jay-tau** [jmerle/competitive-companion#280]
In the case of Codeforces problems, we see that the letter is included in the `"name"` like `G. Castle Defense` has the letter 'G'.
Similarly, it would be nice if the CSES problems when parsed would include the problem number as well. For example, https://cses.fi/problemset/task/1091 would have the name `1091. Concert Tickets` instead of just `Concert Tickets`, which is what is currently present

**Comment by jmerle** [comment]
Competitive Companion uses the problem name displayed by the online judge, so if the judge does not include the problem number/letter in the problem name, then neither does Competitive Companion. I'm not planning on changing that. There is enough information in the extracted data to prefix CSES problem names with the problem number in external tools.
