### ISSUE TITLE
Can't parse problems from yosupo's Library Checker

### ISSUE THREAD

**Issue by dnx04** [jmerle/competitive-companion#285]
Steps to reproduce:
- Run Competitive Companion on any problems on https://judge.yosupo.jp/

![image](https://user-images.githubusercontent.com/86938955/184272796-98ef5fd1-091d-48d9-9f00-d9dcdcdcad0a.png)

![image](https://user-images.githubusercontent.com/86938955/184272878-e6a44a9a-1830-4f2a-b019-5b494d1017a0.png)

Expected results:
- CC should be able to parse all problems on Library Checker once again.

**Comment by jmerle** [comment]
Fixed by #281.
