### ISSUE TITLE
File Name issue in java!

### ISSUE THREAD

**Issue by vasanthgk02** [jmerle/competitive-companion#286]
Can you add a feature to create files in java with only supported characters for variable name ( for ex  A_2_-_3_Moves to A_2_3_Moves i.e. to remove all the unsupported characters )? So it will be helpful for java programmers to create public class same as file name!

**Comment by jmerle** [comment]
Competitive Companion only parses problems and sends the extracted data to external tools. Creating new files and naming them appropriately are tasks that should be (and are) implemented in external tools, not in Competitive Companion itself.
