### ISSUE TITLE
Unable to parse task on CodeJam new Platform

### ISSUE THREAD

**Issue by coderbond007** [jmerle/competitive-companion#29]
After the recent changes in the CodeJam environment, parser is not working at all. Can you please fix the issue as the new season of KickStart is starting on 24 March? Thanking You.

**Comment by jmerle** [comment]
I will fix this bug and #28 on March 21 (which means you have it at last on March 22, depending on when your browser decides to update it's extensions).

**Comment by jmerle** [comment]
Fixed in 69dba6157c2d4295514971cd536c58f13793ff62, will be released in a new version in a few hours.

**Comment by jmerle** [comment]
I have released the new version (2.6.1) to the Chrome Web Store and Mozilla's AMO. Your browser should auto-update the extension within 24 hours.
