### ISSUE TITLE
Please support HUSTOJ

### ISSUE THREAD

**Issue by ghost** [jmerle/competitive-companion#297]
Here is the source of HUSTOJ : https://github.com/zhblue/hustoj
and as I know there are many college oj in China is based on this project such as acm.ocrosoft.com.
This is an example link to a problem : http://acm.ocrosoft.com/problem.php?cid=3405&pid=1

**Comment by jmerle** [comment]
Generic support for all online judges that use HUSTOJ is next to impossible because of HUSTOJ's customizability. I added support for ZUFEOJ in 8e436dee30fbe6a6a501843cb162d84f46f54c6a which will be released soon.
