### ISSUE TITLE
Two days ago the extenstion was working for this problem today when I am trying it is not working for any of the problem. I have tried some other extensions as well it is also not working. https://www.codechef.com/problems/PRIMEDICE 

### ISSUE THREAD

**Issue by kirithiv2000** [jmerle/competitive-companion#302]

**Comment by Excitedcod** [comment]
same here 
![image](https://user-images.githubusercontent.com/93692148/202962906-2151c537-0975-42de-8983-58a0e0d7b5e8.png)

**Comment by ravikumar9519** [comment]
same problem

**Comment by rhimmaste** [comment]
Problem started 2 days ago. Works fine in codeforce.

**Comment by jmerle** [comment]
Fixed in 2af88ab8da93e4d9286268dcd4f86bba2b465b17, will be released within 24 hours. Thanks for reporting the issue!
