### ISSUE TITLE
problem statement

### ISSUE THREAD

**Issue by Gr-Nobel** [jmerle/competitive-companion#304]
I want to get the problem statement either in comments or in a separate markdown file so that I don't have to open the browser again.

**Comment by jmerle** [comment]
I'm not going to implement this. A [similar request](https://github.com/jmerle/competitive-companion/issues/3#issuecomment-381477053) was made 4.5 years ago, it's a bit old but my answer to this suggestion is the same. That request was slightly different, but extracting the problem statement inherits most of the problems that extracting the full HTML does.

Besides, if you are okay with having the problem statement in a separate Markdown file I think you can already achieve your needs without this request. If you were planning to open the Markdown file side-by-side next to your code file, you can just resize your editor and your browser to each take up half of the screen to get the same effect. If you were not planning to have them side-by-side, there is little difference in switching between files and switching between editor and browser.

**Comment by Gr-Nobel** [comment]
may be in commets would be really great.

**Comment by Gr-Nobel** [comment]
extracting the full problem in the comments would help focus.
I would just phrase the full contest and set a personal rule not to leave sublime without finishing the problems..
besides chrome takes a lot of juices from my pc.

**Comment by jmerle** [comment]
My answer stays the same, extracting problem statements is a complicated task with several big hurdles (inline styling, MathJax blocks, images, tables, etc.), and it'd take a long time to implement correctly for all 70+ online judges that this project supports. In my opinion the "focus boost" that you describe does not outweigh the complexity of implementing this feature.

Also: the data Competitive Companion sends to external tools already includes the URL to the problem. If you insist on having problem statements in your code, you can always write your own tooling around that URL to extract the problem statement yourself. This way you can limit yourself to just the judges that you use, and skip parsing elements that you don't care about (like MathJax blocks, tables, images, etc.).
