### ISSUE TITLE
The test cases are not being parsed in codechef due to their CodeChefNewProblemParser.

### ISSUE THREAD

**Issue by Chikzz2001** [jmerle/competitive-companion#306]
In the CodeChef platform the test cases are not being parsed now but previously it worked. Please see to it.
visit any question to check the issue.
eg: https://www.codechef.com/problems/GOODBINSTR

**Comment by jmerle** [comment]
This issue was fixed in 2.38.0 which was released 12 hours before you created this issue. Your browser probably didn't auto-update the extension yet, please make sure you are running the latest version (you can re-install the extension to force an update) and try again.
