### ISSUE TITLE
Not working with codechef

### ISSUE THREAD

**Issue by Prabalpsingh7115** [jmerle/competitive-companion#308]
The companion was not working .Yesterday I found and attaching the snap of error for the same.
![Screenshot 2022-11-25 210222](https://user-images.githubusercontent.com/97095719/204016798-edef6dae-aec5-4e83-8d59-a30ad60405e2.png)

**Comment by jmerle** [comment]
This issue was fixed in 2.38.0 which was released 2 days ago. Your browser probably didn't auto-update the extension yet, please make sure you are using the latest version (you can re-install the extension to force an update) and try again.
