### ISSUE TITLE
parsing error open kattis

### ISSUE THREAD

**Issue by gilcu3** [jmerle/competitive-companion#309]
I am getting this error:
```
TypeError: t[0] is undefined
    parse moz-extension://3517dc7c-6cc9-44c7-a6fc-a27dab54e5b1/js/common.js:1
    parse moz-extension://3517dc7c-6cc9-44c7-a6fc-a27dab54e5b1/js/common.js:1
    l moz-extension://3517dc7c-6cc9-44c7-a6fc-a27dab54e5b1/js/content.js:1
    e moz-extension://3517dc7c-6cc9-44c7-a6fc-a27dab54e5b1/js/content.js:1
    promise callback*e moz-extension://3517dc7c-6cc9-44c7-a6fc-a27dab54e5b1/js/content.js:1
content.js:1:415
 
```
when trying to parse this problem: [open kattis](https://open.kattis.com/contests/nwerc2021open/problems/accessdenied)

Other problems work ok

EDIT: sorry now I noticed it is an interactive problem, closing...

**Comment by jmerle** [comment]
It's not supposed to crash on that problem though, that's fixed in 96a4680d889ee0a8bccd8e56ae85411a9a770798. The change will be released within an hour, thanks for reporting the issue!
