### ISSUE TITLE
codechef parsing issue - only one test case is parsed

### ISSUE THREAD

**Issue by venkatvb** [jmerle/competitive-companion#31]
Hi, 

First of all, competitve-companion plugin is awesome. Thanks for the amazing work!

The following code chef problem has two test-cases but only one is parsed.

URL: https://www.codechef.com/APRIL19B/problems/MAXREM 

<img width="970" alt="codechef parsing issue" src="https://user-images.githubusercontent.com/4996292/55633630-704b9780-57da-11e9-86c3-b8dbe723c932.png">

P.S: I'm using Hightail along with competitive-companion

**Comment by jmerle** [comment]
Fixed in bb570321e6ca9b37b30dbc8447e5e43d66c71885 which will be released in a new version somewhere in the next 24 hours. Thanks for reporting the issue and sorry for the delay!
