### ISSUE TITLE
Parsing Error on Open Kattis

### ISSUE THREAD

**Issue by luffingluffy** [jmerle/competitive-companion#310]
Kattis has updated their UI and thus the parser no longer works.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/66120338/206483394-e34c8faf-fd8e-46c8-9625-c42610ac1357.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/66120338/206483461-745a967b-b3b1-4bee-9f24-e437255629c6.png">

**Comment by jmerle** [comment]
Fixed in f335eee9b7d34210ff0d74594db43a8c14188638, will be released within a few hours. Thanks for reporting the issue!
