### ISSUE TITLE
Couldn't run the tool

### ISSUE THREAD

**Issue by leo-ai-for-trading** [jmerle/competitive-companion#314]
<img width="915" alt="Screenshot 2022-12-20 alle 23 45 30" src="https://user-images.githubusercontent.com/70145737/208781012-0f650785-5398-4bc5-977c-13ba99e9f647.png">

[link`RECNDSTR`](https://www.codechef.com/problems/RECNDSTR)

**Comment by jmerle** [comment]
Fixed in 130188a8c386b361cffa99ede41b90434cfef939, will be released within a few hours. Thanks for reporting the issue!
