### ISSUE TITLE
Cant use the companion tool

### ISSUE THREAD

**Issue by ayushkumar146** [jmerle/competitive-companion#315]

**Comment by vasu52** [comment]
Today on Code Chef, Companion Tool shows error while parsing.
I think it's because of the updates on the Code Chef Website.
![image](https://user-images.githubusercontent.com/110038788/208956601-6424dfc9-2089-4176-8fd8-67eab8dfe104.png)

**Comment by STORMPEGASUS** [comment]
today on codechef companion tool failed to load

**Comment by jmerle** [comment]
Fixed in 130188a8c386b361cffa99ede41b90434cfef939, will be released within a few hours. Thanks for reporting the issue!
