### ISSUE TITLE
Can't use it in codechef anymore ??

### ISSUE THREAD

**Issue by Ri-2020** [jmerle/competitive-companion#316]

**Comment by Ri-2020** [comment]
I cannot parse it is giving some console error

Something went wrong while running Competitive Companion's CodeChefNewProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).

the following is printing in the console
TypeError: Cannot read properties of null (reading 'textContent')
    at CodeChefNewProblemParser.parse (common.js:1:338245)
    at async l (content.js:1:312)

**Comment by Rohit-max101** [comment]
Yes it is not parsing the codechef problems anymore

**Comment by jmerle** [comment]
Fixed in 130188a8c386b361cffa99ede41b90434cfef939, will be released within a few hours. Thanks for reporting the issue!
