### ISSUE TITLE
extension not working on codechef.

### ISSUE THREAD

**Issue by cryptic-pr03** [jmerle/competitive-companion#318]
- Link : https://www.codechef.com/problems/GCDQ

![image](https://user-images.githubusercontent.com/92126782/209436119-dfdf1f12-a63c-40f9-9153-e1f2f1c03b07.png)

**Comment by rockshivam999** [comment]
facing the same issue

**Comment by iamheavymetalx7** [comment]
Yeah, facing the same issue

**Comment by jmerle** [comment]
This issue was fixed in version 2.38.2. You can either wait for your browser to auto-update the extension (usually happens within 24 hours after an update, 2.38.2 passed review on the Chrome Web Store 2 hours ago and on Mozilla's AMO 22 hours ago) or force an update by re-installing the extension.
