### ISSUE TITLE
not working on kattis

### ISSUE THREAD

**Issue by Q23RF** [jmerle/competitive-companion#320]
[link](https://open.kattis.com/problems/friday)
![螢幕截圖 2022-12-25 12 04 40](https://user-images.githubusercontent.com/97279294/209458343-26c9345f-9be1-4c12-bea8-975ad01afcb5.png)

**Comment by jmerle** [comment]
This issue was fixed in version 2.38.2. You can either wait for your browser to auto-update the extension (usually happens within 24 hours after an update, 2.38.2 passed review on the Chrome Web Store 2 hours ago and on Mozilla's AMO 22 hours ago) or force an update by re-installing the extension.
