### ISSUE TITLE
How to judge with warnings?

### ISSUE THREAD

**Issue by Leaf-Coder** [jmerle/competitive-companion#325]
When the compiler gives warnings (no errors), the extension will not judge the testcases.

**Comment by jmerle** [comment]
I have no idea what you mean, Competitive Companion does not "judge testcases". Can you please share a URL to a problem or contest on which you're experiencing this issue?

**Comment by Leaf-Coder** [comment]
Hello the developer

Sorry that I didn't make sense. I meant "Run Testcases". I found that it works correctly now and I can't duplicate that issue anymore. Maybe I made a mistake. Thanks for your help.
