### ISSUE TITLE
REQUEST to add a PARSER for LEETCODE

### ISSUE THREAD

**Issue by ansh04012020** [jmerle/competitive-companion#332]
i am practicing on leet code. i want to have  companion for help

**Comment by ansh04012020** [comment]
Please Try to include.

**Comment by jmerle** [comment]
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+GeeksforGeeks+OR+Geeks), please see #245 for more information.
