### ISSUE TITLE
Bug in NowCoder

### ISSUE THREAD

**Issue by zixiangcode** [jmerle/competitive-companion#333]
Problem like the one on this page cannot be fastened using the plugin to parse https://ac.nowcoder.com/pat/5/problem/4109，please fix it，thank you！
这个页面上的题目无法用插件复制https://ac.nowcoder.com/pat/5/problem/4109，是不是出bug了。感觉是兼容问题。请尝试修复。谢谢。

**Comment by rogeryoungh** [comment]
Currently only supports [牛客比赛(contests)](https://ac.nowcoder.com/acm/contest/vip-index) and  [牛客题库(problems)](https://ac.nowcoder.com/acm/problem/list).

当前仅支持比赛和题库。用牛客 pat 的人感觉比较少，你可以去 pta 交。

**Comment by jmerle** [comment]
Added in 21f2ac255952ec3ea8efa1a6675ff45e2f8f67d3, will be released within an hour. Thanks for reporting the issue!
