### ISSUE TITLE
PTAProblemParser: input/output samples are parsed incorrectly with extra code blocks exist

### ISSUE THREAD

**Issue by Just-Prog** [jmerle/competitive-companion#338]
### Problem

Extra code blocks in the problem description can cause input/output samples to be incorrectly parsed.

This bug can be reproduced easily.

Example: https://pintia.cn/problem-sets/994805046380707840/exam/problems/994805122985476096

### Screenshot (PTA):

![image](https://user-images.githubusercontent.com/62735122/227511946-c3f05d69-2d6a-44cb-b7b8-36ae1b28bd79.png)

### Screenshot (CP Editor):

![image](https://user-images.githubusercontent.com/62735122/227512082-891bdd9d-fe8a-45cb-b8ad-9f1ca3386c30.png)

### Screenshot (Competitive Programming Helper (cph) (Visual Studio Code)):

![image](https://user-images.githubusercontent.com/62735122/227512278-e1c233ec-9b42-4b2e-bfa8-0ae2c10eab2e.png)

**Comment by jmerle** [comment]
Fixed in 3f3a8d291fd1aa4dcf2909de30dc07a4e5ce32b5, will be released within a few hours. Thanks for reporting the issue!
