### ISSUE TITLE
Parsing for arena.moi

### ISSUE THREAD

**Issue by omaaarde** [jmerle/competitive-companion#339]
Can u make it working for this website https://arena.moi/problems/

**Comment by jmerle** [comment]
I can't access arena.moi, and it seems like [it's not just me](https://downforeveryoneorjustme.com/arena.moi). Can you still access it?

**Comment by jmerle** [comment]
Seems like MOI Arena is online again, added in c4cecfcbc35eb0ca5fbf385ccfeba9dc43fca23d, will be released within an hour.
