### ISSUE TITLE
C+++ IDE's repo is 404 now

### ISSUE THREAD

**Issue by Find-NICK** [jmerle/competitive-companion#346]
In [`README.md`](https://github.com/jmerle/competitive-companion/blob/master/README.md),C+++ IDE is listed in "Supported tools".
But it's repo is 404 now.
In fact,user "23786",the devloper of C+++ IDE,is also disappeared in Github.[^1]

I can only find [this one:`bohanjun/Cppp-IDE`](https://github.com/bohanjun/Cppp-IDE),bohanjun's fork(maybe),
and [Cppp-team(don't have C+++ IDE's repo)](https://github.com/Cppp-team).

[^1]: In `bohanjun/Cppp-IDE` ,there's only AFObject's commits.
So maybe "23786" is now "AFObject".

**Comment by jmerle** [comment]
Removed in 062df20d927892ca38c88f9a1462b0f31c099607. https://github.com/bohanjun/Cppp-IDE may indeed be the new repository but it doesn't seem to contain support for Competitive Companion. If the developer(s) of C+++ IDE reads this: feel free to let me know the new official repository in this issue or a new one.
