### ISSUE TITLE
Create one for Safari as well?

### ISSUE THREAD

**Issue by ninadsutrave** [jmerle/competitive-companion#347]
It Is really easy to convert existing chrome extensions to Safari. Can you please publish one for Safari as well?

**Comment by jmerle** [comment]
No, I can't. No matter how easy it may be to convert a Chrome extension to work on Safari, publishing Safari extensions requires Xcode and Apple Developer Program membership, and properly supporting issues that come up in Safari extensions requires being able to reproduce such issues in Safari locally. Xcode, Apple Developer Program membership, and Safari are only available to people that work on (or possess) a Mac, which I don't.

**Comment by ninadsutrave** [comment]
Okay thankk you!
