### ISSUE TITLE
Feature request: Split a test into smaller cases

### ISSUE THREAD

**Issue by TroySigX** [jmerle/competitive-companion#350]
For a test with multiple test cases. e.g let there be 4 test cases, and each test takes a and b as inputs:
```
4
1 2
2 3
4 5
5 5
```
Conventionally, `companion` would just store this test as one big test, but instead, I'd like it to be broken down into smaller cases (e.g breaking them into 4 cases), with each case in the following format:
```
1
a b
```

This makes it easier to debug while in the contest

**Comment by jmerle** [comment]
I understand the request, but it's out-of-scope for Competitive Companion. The goal of this extension is to parse raw problem information (such as the sample cases) from online judges, and to send that data to external tools that can do something useful with it. Any post-processing on that data, be it [reformatting titles](https://github.com/jmerle/competitive-companion/issues/258), splitting up test cases, or anything else, should be done by these external tools.
