### ISSUE TITLE
USACO parser is not working.

### ISSUE THREAD

**Issue by cplayer** [jmerle/competitive-companion#36]
When I solving https://train.usaco.org/usacoprob2?a=8Vt1VSIM12q&S=subset, the usaco parser is not working.
Maybe the https is the reason?

**Comment by jmerle** [comment]
Yep, seems like https is the reason. I'll release a new version tonight that fixes the issue.

**Comment by jmerle** [comment]
I have released the new version (2.7.2) to the Chrome Web Store and Mozilla's AMO. Your browser should auto-update the extension within 24 hours.
