### ISSUE TITLE
Extension not working on qojWebsite

### ISSUE THREAD

**Issue by sagnikghoshcr7** [jmerle/competitive-companion#372]
Extension not working on [qoj](https://qoj.ac/) Website

**Comment by jmerle** [comment]
Competitive Companion does not have a QOJ parser at the moment, and I'm not adding it neither. The reason for that is that unfortunately most of QOJ's problems appear to be served as PDF, without a common format between those PDFs. This makes parsing it programmatically a nightmare, as you'd have to write detectors and parsers for all different formats used in QOJ PDFs, which I do not consider to be worth the effort.
