### ISSUE TITLE
Contests are not parsed in full

### ISSUE THREAD

**Issue by adambenali** [jmerle/competitive-companion#38]
First of all I wasn't sure whether to make this issue here or in CHelper/JHelper repo, as there seems to be a problem with both.

### The problem
When parsing a full contest, I've noticed that the parsing stops after a number of tasks. It's not a problem with the parsing itself as the debug mode shows that they are all correctly parsed.

At first, it seemed like the problem happened with Google Chrome and on Windows only. Not on Firefox, and not on Linux. Using Chrome and Windows, the parsing always stops after exactly 6 tasks. But then, after some investigation, I've come to the conclusion that it depends on the number of problems to parse. I was able to reproduce these symptoms on Linux with Chrome as well with a large enough contest.

**Fastest way to reproduce it:** Try to parse a contest with more than 6 tasks on Windows using Chrome.

### The cause
So I've done some investigation and for me there are two reasons for this.
- First, the simple servers created by CHelper/JHelper do not make a response, so after acquiring the data from competitive companion, they sort of "hang".
- Second, there is a timeout of 500ms set to the AJAX requests made to the server, which, on Chrome, results in all the requests still blocked after 500ms, to be canceled.

**Why stop after exactly 6 tasks ?** Because the maximum number of concurrent HTTP connections per hostname in Chrome and Firefox is 6. So the server processes the first 6 requests, and the subsequent ones are cancelled.

### My suggestion
Ideally, the solution would be to make fewer AJAX calls by making one JSON with all the contest data, but that would break compatibility with the tools.
Otherwise, I would suggest to either remove the timeout of 500ms, provided that the tool's server always responds, or to increase it significantly. In both cases, the server has to respond in order not to block the following requests.

**Why is the problem more explicit on Windows using Chrome ?** Chrome on Windows seems to process AJAX calls slower than other browsers, something I still cannot understand. Maybe a bug ?
Here is a comparison between what happens making 10 AJAX requests on Chrome, on Windows and Linux. (The timeout for the calls is set to 5000ms)

Windows : 
![image](https://user-images.githubusercontent.com/23511758/58583780-0f2dc680-8255-11e9-8fc3-d8ced2e0dc43.png)

Linux :
![image](https://user-images.githubusercontent.com/23511758/58583690-dee62800-8254-11e9-8207-0c128ce3a52a.png)

Notice how the last 4 requests take more than 500ms to be processed. They would just be cancelled if I set the timeout to 500ms.

**Comment by AlexeyDmitriev** [comment]
I am not really familiar with the web stack and Java stack (only did networking stuff with C/C++) but I find it really strange that after we close the socket(try-with-connection on Socket class does that I think) browser continues to wait something. It should have received 0 from read syscall and understood that connection is closed. So seems like a Chrome bug to me. Is behaviour same on Firefox/IE?

Anyway, I'll apply the patch if you say if you say it fixes the problem.

**Comment by jmerle** [comment]
Hmm. I must admit that I haven't done extensive testing on Windows (am more of a Linux guy), but this seems like a pretty serious issue. I can't really see if this is a problem with JHelper's implementation, but if it is it most likely means CHelper is also affected (assuming the former is still mostly a CLion-compatible clone of the latter).

Although your fix seems valid, I think there is another way. Currently the extension sends all requests at once. Instead, we could send them one at a time. This way the extension never hits the 6 request limit, without setting an arbitrarily high timeout and without breaking compatibility with existing listeners. I can experiment with this idea tonight/tomorrow.

**Comment by AlexeyDmitriev** [comment]
If I understand original post correctly, it will not help much, because the previous connection will be considered not finished for 500ms. I will be glad to be wrong, though

**Comment by jmerle** [comment]
Yea, the downside would be that it limits the amount of problems sent to 2 per second, unless the listening server sends a response within the timeout.

**Comment by adambenali** [comment]
> I am not really familiar with the web stack and Java stack (only did networking stuff with C/C++) but I find it really strange that after we close the socket(try-with-connection on Socket class does that I think) browser continues to wait something. It should have received 0 from read syscall and understood that connection is closed. So seems like a Chrome bug to me. Is behaviour same on Firefox/IE?
> 
> Anyway, I'll apply the patch if you say if you say it fixes the problem.

Yes, the same behavior seems to happen with all other browsers. They all wait for a response from the server even though the socket was closed.
This means that parsing a large enough contest (_i.e_ for which the dispatching of the requests would take more than 500ms) would explicit this problem, independently of the environment or the browser.

**Comment by jmerle** [comment]
Fixed in 35d6609 and ffe3a8a. Requests are now sent one by one instead of parallel to each other. This will prevent any issues with the parallel request limit.

I also updated the way data is sent to CHelper (and therefore JHelper). After some debugging I found that CHelper does not show the "Create task" dialog until the request is closed. Although this somewhat makes sense, the previous implementation of sending data to CHelper was somewhat of a clone of how the original extension sends data: send data > wait for 500ms timeout to hit > request is aborted and create task dialog is shown. I have changed this so that it now automatically closes the request when all data has been transferred. This change makes requests to CHelper way faster, from the original 500ms to <10ms. This change also invalidates my previous comment about the 2 problems per second send limit when using CHelper and makes sending problems sequentially possible without affecting performance.

I know the above might sound vague, but I can't really explain it better. Look at the two commits if you want to see what changed.

These changes will go live in a new version in about an hour.

**Comment by AlexeyDmitriev** [comment]
Could you please clarify whether I should add response on the JHelper side or it now works fine as is?

**Comment by jmerle** [comment]
It now works fine as is.

**Comment by AlexeyDmitriev** [comment]
Thanks!
