### ISSUE TITLE
cses.fi can't parse tests

### ISSUE THREAD

**Issue by qixiao986** [jmerle/competitive-companion#382]
<img width="878" alt="Screenshot 2023-10-04 at 12 56 59" src="https://github.com/jmerle/competitive-companion/assets/3962171/9e223814-6fe3-4e71-92f8-5711b0aa865e">

**Comment by jmerle** [comment]
Fixed in 0c040e3ae9d64e3b728ae9ec44c4a768d4e84dc5, will be released within a few hours. Thanks for reporting the issue!
