### ISSUE TITLE
Extension is not working on Coding Ninja and leet code problems

### ISSUE THREAD

**Issue by amitku2003** [jmerle/competitive-companion#383]
I am not able to figure out the problem. Please fix this problem.

**Comment by jmerle** [comment]
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+Ninja+OR+CodeStudio), please see #245 for more information.
