### ISSUE TITLE
How to set up General: Save Location Location 

### ISSUE THREAD

**Issue by LXT2000** [jmerle/competitive-companion#388]
It doesn't work after I set it up, and the path is wrong. How should I set it correctly?
<img width="542" alt="image" src="https://github.com/jmerle/competitive-companion/assets/87964117/73e4a901-fbd2-4d90-a7bf-a2ac5312e521">
<img width="662" alt="image" src="https://github.com/jmerle/competitive-companion/assets/87964117/53dbb370-eb77-4b86-bed5-6835b444a920">
<img width="538" alt="image" src="https://github.com/jmerle/competitive-companion/assets/87964117/41ce6f1e-31dc-4a8f-ae37-539d41a60041">

**Comment by jmerle** [comment]
This is the Competitive Companion repository, I can't help you with CPH issues. I think the right place to ask/report this would be the CPH repository ([agrawal-d/cph](https://github.com/agrawal-d/cph)).

**Comment by LXT2000** [comment]
ok,thanks
| |
bill
|
|
***@***.***
|


---- Replied Message ----
| From | Jasper van ***@***.***> |
| Date | 10/17/2023 13:04 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jmerle/competitive-companion] How to set up General: Save Location Location (Issue #388) |

Closed #388 as completed.
