### ISSUE TITLE
Request for IT Coder HUTECH Support in Competitive 

### ISSUE THREAD

**Issue by buiphukhuyen** [jmerle/competitive-companion#389]
I am writing to inquire if it would be possible to request your support in adding support for the IT Coder HUTECH system to CC. IT Coder HUTECH is an emerging platform that hosts a collection of coding problems and contests. It has been gaining popularity among students and competitive programmers at our institution.

The IT Coder HUTECH platform offers a variety of problems (available at https://itcoder.hutech.edu.vn/problem/index) and hosts contests regularly (accessible at https://itcoder.hutech.edu.vn/contest/index). Having CC support for IT Coder HUTECH would greatly benefit our community and allow us to seamlessly fetch test cases and simplify the submission process.

Your support in this matter would be immensely appreciated and would contribute to making Competitive Companion even more versatile and helpful for the coding community. We believe that the inclusion of IT Coder HUTECH would open up new possibilities for users, making it an essential tool for competitive programmers at our institution.

Thank you for your time and consideration.

**Comment by touhidurrr** [comment]
thanks for the issue. i will look into it inshallah.

**Comment by buiphukhuyen** [comment]
You can use this account to log in to the system:
username: sinhvientest
password: hutech@sv
Thanks.
