### ISSUE TITLE
There is no parser for Leetcode

### ISSUE THREAD

**Issue by opticSquid** [jmerle/competitive-companion#396]
Leetcode is a widely used platfrom for practicing DSA and also competing. There should be problem parser for Leetcode.
![image](https://github.com/jmerle/competitive-companion/assets/59192460/01f98ea6-e5c5-4286-b004-ecb03ed92be7)

**Comment by jmerle** [comment]
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Comment by opticSquid** [comment]
ok I understand
