### ISSUE TITLE
Test cases are incorrectly patsed for https://cpython.uz/

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#399]
Namely, new lines are not included — everything is parsed into single line without even space.

**Comment by jmerle** [comment]
Version 2.48.0 got successfully published to the Chrome Web Store before I started refactoring, so on second thoughts I've just released version 2.48.1 which includes the fix for this issue. It's already live for Firefox and is pending review on the Chrome Web Store.
