### ISSUE TITLE
fail at open.kattis.com

### ISSUE THREAD

**Issue by kenzanin** [jmerle/competitive-companion#400]
failed to fetch problem at kattis.com

https://open.kattis.com/problems/maeting

with message 
Something went wrong while running Competitive Companion's KattisProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).

and this happen on every page/problem.

**Comment by jmerle** [comment]
See https://github.com/jmerle/competitive-companion/issues/398#issuecomment-1846572915.

**Comment by kenzanin** [comment]
thank you.
