### ISSUE TITLE
开通OJ测试点拉取

### ISSUE THREAD

**Issue by stackedu** [jmerle/competitive-companion#404]
OJ链接：msoj.stackedu.com
OJ名称：MSOJ

**Comment by jmerle** [comment]
I don't understand Chinese, but based on Google Translate I guess you're asking for MSOJ support. It appears that this judge requires you to login before being able to view problems, but guests cannot register an account. I can't add a parser for problems which I can't open myself, but you're welcome to contribute one yourself in a PR.
