### ISSUE TITLE
2.8.0 broke AtCoder parsing for IntelliJ CHelper

### ISSUE THREAD

**Issue by anandoza** [jmerle/competitive-companion#41]
Hi, during the AGC this morning, I was unable to use this extension to parse problems to CHelper. In IntelliJ, the Event Log said "CHelper: Unknown task type from Chrome parser: null"

After the contest I looked into it and saw there was an update recently, and installed 2.7.3 from this github -- and it worked again.

**Comment by jmerle** [comment]
Which browser and operating system are you using? I cannot reproduce this on Chrome 74 or Firefox 67 on Ubuntu 18.04.

**Comment by jmerle** [comment]
Also, please send the link to the page where you tried parsing using 2.8.0.

**Comment by anandoza** [comment]
I tried it on https://atcoder.jp/contests/agc034/tasks/agc034_a
I'm using Chrome 74 on Mac OS 10.14.5

I also tried it on some older AtCoder contests that I used it on successfully before and it didn't work, but it all worked once I used the old version of the extension.

Thanks for the quick reply and for making this great extension!

**Comment by jmerle** [comment]
I have published version 2.8.1 which reverts a performance improvement in 2.8.0 which I suspect to be causing this issue. It might take up to 24 hours for it to be available everywhere. Could you please try the new version when it's available and see if the bug is fixed?

**Comment by anandoza** [comment]
Hi, sorry for the late slow reply.

I'm using version 2.8.3 now, and it works great! Thank you.
