### ISSUE TITLE
Questions Nomenclature

### ISSUE THREAD

**Issue by balajirai** [jmerle/competitive-companion#418]
Hey there, I appreciate the effort behind this project.
I have one suggestion regarding it. 
- It would be quite nice if the naming of question includes the quesion I'd in it.  (`Codeforces`)
- For example: Instead of `B_Two_Divisors.cpp` , `1916B_Two_Divisors.cpp` would really be helpful in revisiting the problem if required.

**Comment by jmerle** [comment]
I understand what you want to do, but I consider this out-of-scope for Competitive Companion. Competitive Companion's task is to extract the original problem data as-is, so if a problem page (like on Codeforces) does not show the id in the problem title, then Competitive Companion won't magically add it. The extracted data does include the problem's URL though, so external tools can extract the problem ID from there and add it to the title if they want to provide such a feature to their users.
