### ISSUE TITLE
Can't Parse wiith CodeChefContest

### ISSUE THREAD

**Issue by MussaddikKhan** [jmerle/competitive-companion#420]
Something went wrong while running Competitive Companion's CodeChefNewProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).

showing this error

**Comment by 1TusharSharma1** [comment]
Happening with me too!

**Comment by jmerle** [comment]
This is a duplicate of #410, for which the fix was already released in version [2.50.0](https://github.com/jmerle/competitive-companion/releases/tag/2.50.0).
