### ISSUE TITLE
Custom rules for UOJProblemParser does not work

### ISSUE THREAD

**Issue by 52871299hzy** [jmerle/competitive-companion#427]
When using the custom rules for a UOJ-based OJ [problem](http://noi.ac/problem/1) I get this console log:

```
TypeError: Cannot read properties of undefined (reading 'parse')
    at parse (content.js:49:6070)
    at handleMessage (content.js:49:7106)
```

![image](https://github.com/jmerle/competitive-companion/assets/33828093/a6341893-7668-4b76-b50e-e383f9ff469b)

It seems that `getParserByName('UOJProblemParser')` returns `undefined` because the UOJProblemParser instance in `parsers` has `.constructor.name === '_UOJProblemParser'`, which doesn't match the given parser name.
![image](https://github.com/jmerle/competitive-companion/assets/33828093/91b35480-3ccc-46b1-aa16-449c3e686cc9)

**Comment by jmerle** [comment]
ESBuild appears to prefix classes with static members with an underscore. Fixed in 5458859e64208e80d0c1d5907356834702ee76fb, will be released soon. Thanks for reporting the issue!
