### ISSUE TITLE
Could Not Determine Parser For USACO

### ISSUE THREAD

**Issue by roirepus** [jmerle/competitive-companion#429]
Competitive Companion could not determine which parser to parse this page with. Please right-click on the plus icon and select the parser to use via the "Parse with" context menu. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).

Issue was faced on FIREFOX and BRAVE broswsers while attempting problems on USACO

https://usaco.org/index.php?page=viewproblem2&cpid=591

**Comment by roirepus** [comment]
'http://www.usaco.org/current/index.php*',
      'http://www.usaco.org/index.php*',
      'http://usaco.org/current/index.php*',
      'http://usaco.org/index.php*',

these lines in src/problem/ parser.ts seems to be the issue. Should not it be https? I am not sure if what I am saying makes any sense, I'm pretty new here. @keerthivasansa @jmerle

**Comment by jmerle** [comment]
USACO switching from http to https does indeed seem to be the issue, fixed in 6008eb437772540bf968223160bd23be79eeb22c, will be released within 24 hours. Thanks for reporting the issue!
