### ISSUE TITLE
acmicpc.net parser not working properly

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#430]
So, for me
- task parser works, but I have to specify judge each time
- contest parser does not work after specifying judge:
` Failed to parse task 11: TypeError: Cannot read properties of null (reading 'textContent')
    at BaekjoonOnlineJudgeProblemParser.parse (content.js:13:11667)
    at BaekjoonOnlineJudgeContestParser.parseTask (content.js:13:9243)
    at async Promise.all (index 10)
    at async BaekjoonOnlineJudgeContestParser.parse (content.js:13:7842)
    at async parse (content.js:49:6123)`

**Comment by EgorKulikov** [comment]
Sorry, forgot to include url: https://www.acmicpc.net/contest/view/1238

**Comment by EgorKulikov** [comment]
It works now, idk what was wrong. Although it is a second time it does not work during the contest and works afterwards.

**Comment by jmerle** [comment]
That sort of makes sense, after the contest links like https://www.acmicpc.net/contest/problem/1238/9 (contest 1238 problem 9) redirect to the "normal" problem pages, like https://www.acmicpc.net/problem/31441 . I don't know what such links redirect to while the contest is ongoing though (if it redirects at all).

**Comment by EgorKulikov** [comment]
> That sort of makes sense, after the contest links like https://www.acmicpc.net/contest/problem/1238/9 (contest 1238 problem 9) redirect to out-of-contest problem pages, like https://www.acmicpc.net/problem/31441 . I don't know what such links redirect to while the contest is ongoing though (if it redirects at all).

They do not redirect. Can you change regexp accordingly?

**Comment by jmerle** [comment]
Thanks for the information. I updated the parser's match patterns in 4bcd903cbde11c17fcc1790fac3566e1661af2f7 and will release that change within a few hours. That should fix the remaining half of this issue, so I'm closing it.
