### ISSUE TITLE
[Request]Could we add a switch on Nowcoder Parser to Change the filenames into English?/能在牛客的parser里加入英文文件名的开关吗

### ISSUE THREAD

**Issue by qwedc001** [jmerle/competitive-companion#431]
如题。主要原因是，vscode的gdb调试不支持中文文件名，编译虽然会成功并且cph也能用，但是如果答案错误想要用到断点调试的功能，目前只能新建一个文件再编译一次。

Request described in the title.
The main reason for the request is that for vscode,gdb doesn't support Chinese characters.Although this doesn't affect the compilation and the cph would work,but it is disturbing when the answer went wrong and I need to add breakpoints and debug.Currently the only solution is to create another one with english filename and no cph and build it again.

理想中的文件名：Nowcoder-contestId-problemId.cpp 

eg.Nowcoder-76133F.cpp

**Comment by qwedc001** [comment]
Extra Request:Same issue on Luogu parser

**Comment by jmerle** [comment]
The problem title in the data sent to external tools is the title as it is displayed on the online judge's website, which may contain filename-unfriendly characters such as forward slashes, colons, and non-ASCII characters. I'm not planning to change that behavior.

If external tools decide to create files based on Competitive Companion's data, it is up to those tools to ensure that files they create have names that are compatible with the user's operating system and tooling. One way of doing that on non-Windows systems is by using the [`languages.java.taskClass`](https://github.com/jmerle/competitive-companion#the-format) property (on Windows systems there are [some reserved file names](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) that are not taken into account for that field). You should send this feature request to the developer(s) of CPH instead.
