### ISSUE TITLE
MendoProblemParser testcase getter problem

### ISSUE THREAD

**Issue by EntityPlantt** [jmerle/competitive-companion#434]
## Problem
Can't fetch testcase data because the query selector is returning the wrong table on some tasks with more `tbody` elements in `taskContentView`. On line 42 `parsed` is null in that case, leading to an error.
https://github.com/jmerle/competitive-companion/blob/6f112b8f24571629638ff549a933f9b94837782e/src/parsers/problem/MendoProblemParser.ts#L42

## Workaround
Until this gets fixed, users can delete all `tbody` elements except the testcases one via the developer tools.

## Fix
Change this code to not run on the first `tbody` element, but on the one that this regex passes (with a `forEach` statement)
https://github.com/jmerle/competitive-companion/blob/6f112b8f24571629638ff549a933f9b94837782e/src/parsers/problem/MendoProblemParser.ts#L40-L43

![error](https://github.com/jmerle/competitive-companion/assets/92634082/c1bba1f9-1129-401c-bd9b-26e43064fbcb)

**Comment by EntityPlantt** [comment]
Forgot to give sample task that has multiple `tbody` elements
https://mendo.mk/Task.do?id=24

**Comment by jmerle** [comment]
Fixed in 0d5bba7c218bc5ba9f75dd7a78967b142dbc75c6, will be released within an hour. Thanks for reporting and investigating the issue!

**Comment by EntityPlantt** [comment]
Nice! Didn't know that `tasks` was a public member of `TestcaseBuilder`, would've made L53 the same in #409 too!
https://github.com/jmerle/competitive-companion/blob/0d5bba7c218bc5ba9f75dd7a78967b142dbc75c6/src/parsers/problem/MendoProblemParser.ts#L53
