### ISSUE TITLE
Add GeeksforGeeks

### ISSUE THREAD

**Issue by Salil03** [jmerle/competitive-companion#44]
You must add https://practice.geeksforgeeks.org. Example: https://practice.geeksforgeeks.org/problems/path-in-matrix/0

**Comment by jmerle** [comment]
Unfortunately, Geeks for Geeks can't be added for a few reasons:
- The problem description which contains the test samples has no structure (it's different between problems), making it very hard to consistently parse it.
- The memory and time limits are nowhere to be found.
- It looks like the website contains a lot of "complete this function, don't use your own template" type of problems, which are completely incompatible with Competitive Companion.

**Comment by krishnakumarg1984** [comment]
Have g4g updated their website to adhere to accepted standards?
