### ISSUE TITLE
Hope to support LanQiao OJ(lanqiao.cn)

### ISSUE THREAD

**Issue by Yerosius** [jmerle/competitive-companion#444]
The LanQiao Cup is a student-oriented algorithmic competition that has emerged and gained popularity in China after 2020 and is open to students from elementary school to graduate school, and it also has its own OJ called **LanQiao OJ** and has weekly competitions, with OJ URL is **lanqiao.cn**, which I hope will be supported!

**Comment by touhidurrr** [comment]
@Yerosius, what is the name of the OJ in english?

**Comment by Yerosius** [comment]
> @Yerosius, what is the name of the OJ in English? Should I call it **LanqiaoOJ** or simply **Lanqiao** ? Also, can you give me a problem link? This website has a lot of pages, ,not sure where the problems are.

such as https://www.lanqiao.cn/problems/

**Comment by touhidurrr** [comment]
> After my checking, its English name is LanQiao Cup OJ, thanks for the reminding.

What does "LanQiao" mean?

**Comment by Yerosius** [comment]
> > After my checking, its English name is LanQiao Cup OJ, thanks for the reminding.
> 
> What does "LanQiao" mean?

This is its Chinese name, directly translated into English as the Blue Bridge Cup(aka BBC).The name probably comes from the Redbridge Cup in CTF.

**Comment by touhidurrr** [comment]
Ok, I tried to login. But there are problems. The site only allows log in via WeChat. I had a WeChat account long time ago with no friends in it. I also uninstalled my WeChat. Now after logging in, they want me to verify myself by scanning a code with previous WeChat (not possible as I uninstalled) or ask a friend to message me a code (also not possible).

Thus I cant login to WeChat and cannot test the OJ myself. Sorry for asking so many questions in the meantime. But I don't think I can work on this OJ now.

**Comment by Yerosius** [comment]
> Ok, I tried to login. But there are problems. The site only allows log in via WeChat. I had a WeChat account long time ago with no friends in it. I also uninstalled my WeChat. Now after logging in, they want me to verify myself by scanning a code with previous WeChat (not possible as I uninstalled) or ask a friend to message me a code (also not possible).好的，我尝试登录。但是存在问题。该网站只允许通过微信登录。我很久以前有一个微信账号，里面没有朋友。我还卸载了我的微信。现在登录后，他们希望我通过扫描以前的微信代码来验证自己（因为我卸载了不可能）或请朋友给我发消息验证码（也不可能）。
> 
> Thus I cant login to WeChat and cannot test the OJ myself. Sorry for asking so many questions in the meantime. But I don't think I can work on this OJ now.因此，我无法登录微信，也无法自己测试OJ。很抱歉在此期间问了这么多问题。但我认为我现在不能在这个 OJ 上工作。

You can also register via phone number.

**Comment by touhidurrr** [comment]
> You can also register via phone number.

Ok it worked. Now let's ask you a question. Which one of these do you think sound right?
1. LanqiaoProblemParser
2. LanqiaoCupProblemParser
3. LanqiaoCupOJProblemParser

**Comment by touhidurrr** [comment]
@Yerosius are you there? I am currently working on this issue.

**Comment by Yerosius** [comment]
> > You can also register via phone number.
> 
> Ok it worked. Now let's ask you a question. Which one of these do you think sound right?
> 
> 1. LanqiaoProblemParser
> 2. LanqiaoCupProblemParser
> 3. LanqiaoCupOJProblemParser

Any of them.
