### ISSUE TITLE
Competitive Companion does not properly work

### ISSUE THREAD

**Issue by SAYAN-DEV-NATH** [jmerle/competitive-companion#457]
Something went wrong while running Competitive Companion's CodeChefNewProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).

**Comment by touhidurrr** [comment]
@SAYAN-DEV-NATH can you share the problem link where the extension broke?

**Comment by jmerle** [comment]
Fixed in 9e66462b232b8c8700563dbf5ec8a511e5b20453, thanks for reporting the issue and sharing the link. Will be released within a few hours.
