### ISSUE TITLE
Allow codeforces parser on *.codeforces.com

### ISSUE THREAD

**Issue by AlexeyDmitriev** [jmerle/competitive-companion#46]
During onsite http://dashaai.contest.codeforces.com was used  but parser was not active

**Comment by AlexeyDmitriev** [comment]
Or maybe even you should be able to parse any site (by choosing parser). you click on plus icon, choose parse as -> codeforces and it parses it. Maybe even remember parser for the site locally

**Comment by jmerle** [comment]
Great idea!

I'll add *.codeforces.com to the Codeforces parsers and release it in a patch update in a few hours. The context menu will come in a separate update, but that might take a week or so because of it's (assumed) complexity.

**Comment by jmerle** [comment]
I have released version 2.8.5 which supports problems and contests on *.codeforces.com subdomains. As usual, it should be available everywhere within 24 hours.

I'll keep this issue open until the browser action context menu you suggested has been implemented.

**Comment by AlexeyDmitriev** [comment]
Thanks!

**Comment by jmerle** [comment]
Sorry for the delay. The context menu is no longer feasible since the extension no longer runs on all url's, making a "Parse as" menu practically useless because it wouldn't be triggerable on a non-supported website. I cannot make the extension run on all url's because then the Chrome Web Store will flag it for manual review everytime, which can delay releases on Chrome for up to two weeks.

**Comment by AlexeyDmitriev** [comment]
Thanks for the feedback.

I'm somewhat surprised there's no option like "run on sites that user whitelisted" or something like that, still *.codeforces.com solved my immediate problem.

**Comment by jmerle** [comment]
I have found a way to support this after all. Version 2.14.0 contains the context menu you suggested:

![](https://i.imgur.com/4ONkEj3.png)

The Firefox version is already live, the Chrome version is currently pending review and should be available soon.
