### ISSUE TITLE
Access revocation

### ISSUE THREAD

**Issue by abdoei** [jmerle/competitive-companion#461]
There is a little bright dot beneath the icon of the extension that indicates that the extension proposes to parse this page for any webpage. This could be eliminated by narrowing the scope of the extension in the manifest to the selected domains.
![image](https://github.com/jmerle/competitive-companion/assets/64744285/0cc01924-e7b3-4b3d-913b-7b0906d70946)

**Comment by jmerle** [comment]
This is a known Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1851083.
