### ISSUE TITLE
Using -fsanitize=address as compile argument randomly gives testcase timed out for some reason

### ISSUE THREAD

**Issue by boasbakker** [jmerle/competitive-companion#464]
![afbeelding](https://github.com/jmerle/competitive-companion/assets/59883944/f13e6393-e497-44e9-96a0-d3292ebb80e8)

When retrying the testcase it doesn´t fail anymore. Mainly happens when testing multiple testcases at a time.

**Comment by boasbakker** [comment]
So with "cph.language.cpp.Args": "-D_GLIBCXX_DEBUG -fsanitize=undefined -ftrapv -g3 -ggdb3 -O0 -Wall -Wextra -Wpedantic -Wshadow -Wno-sign-compare", it runs fine, and with
"cph.language.cpp.Args": "-D_GLIBCXX_DEBUG -fsanitize=address,undefined -ftrapv -g3 -ggdb3 -O0 -Wall -Wextra -Wpedantic -Wshadow -Wno-sign-compare", it sometimes works and sometimes doesn´t with exactly the same code and testcase

**Comment by touhidurrr** [comment]
@boasbakker, this extension only parses the problem statement and provides input / output samples for other extensions to parse. The problem you have reported seems to be related to the project named [cph](https://github.com/agrawal-d/cph). Maybe you should report this issue there?

**Comment by boasbakker** [comment]
Oh oops sorry
