### ISSUE TITLE
question does not appear on vs code

### ISSUE THREAD

**Issue by satyamdeo19** [jmerle/competitive-companion#468]
While clicking on the parser, blue line gets passed but it does not open in vs code . I have only one instance of vs code open .It worked previously quite well

**Comment by jmerle** [comment]
Competitive Companion only parses problem data and sends it to external tools. It sounds like the parsing works fine, and Competitive Companion's "send problem data to external tool" mechanism hasn't changed in a long time, so this is likely an issue in the external tool that you're using. You should send this bug report to the developer(s) of said tool.
