### ISSUE TITLE
Remote address support

### ISSUE THREAD

**Issue by hack1nt0** [jmerle/competitive-companion#472]
Any option to configure the remote ip/host to send json data to?

My usercase is as below:

1. A remote terminal-access develop host, which running a http server that can parse json;
2. personal laptop as client to view html pages;

Thanks for this amazing plugins.

**Comment by jmerle** [comment]
No, this is not possible. The host where the data is sent to must be defined in the extension's manifest that is submitted to the Chrome Web Store and Mozilla's AMO, so it can't be defined dynamically on a per-user basis.

I assume you can run anything you want on your personal laptop. If that's true, you could probably create a simple program that listens for requests from Competitive Companion on your personal laptop and passes the data onto your remote host.
