### ISSUE TITLE
CSES: Parse all problems at once

### ISSUE THREAD

**Issue by aryanshomray** [jmerle/competitive-companion#474]
The current CSES implementation doesn't work for exporting all the problems all at once from the list & its tedious to export it one by one. I think it is better to implement this feature to avoid repetitive tasks. I can write a PR for this task if you agree.

About the implementation, I think it is better to implement it as a separate parser which can parse the problemset list and for each entry it can import problem parser from the existing implementation. Let me know what you think.

**Comment by jmerle** [comment]
I disagree, this is not supported in any other parser and I don't think it's wise to make an exception for CSES.

The problem parsing in Competitive Companion is already pretty quick, hitting Ctrl+Shift+U or pressing the plus button takes a negligible amount of time and effort compared to reading the problem description or thinking about a possible solution. If problem parsing is really the bottleneck in how fast you can progress through the problems of any online judge, you are probably solving problems that are too easy for you.
