### ISSUE TITLE
Not parsing the problems in contests in toph.co

### ISSUE THREAD

**Issue by Ajlanalif** [jmerle/competitive-companion#476]
contest link: https://toph.co/arena?contest=cuss-it-fiesta-2024-inter-university-preliminary#!/p/6685849a231f2b024e8152fc

VM725 content.js:59 TypeError: Cannot read properties of null (reading 'textContent')
    at TophProblemParser.parse (content.js:59:1808)
    at parse (content.js:59:12479)
    at handleMessage (content.js:59:13515)

**Comment by jmerle** [comment]
Fixed in fb325fc6b0b6ebeb72259f1c8af47bf727cdad9c, will be released within 24 hours. Thanks for reporting the issue!
