### ISSUE TITLE
Cannot parse problem on some pages.

### ISSUE THREAD

**Issue by vuthanhtrung2010** [jmerle/competitive-companion#481]
Some pages uses DMOJ but it is a modified UI and components.

![image](https://github.com/user-attachments/assets/2d6cfdb9-c0d4-40f8-8f2a-e45dbcd5c33c)

This is the error I found.
Example page: https://lqdoj.edu.vn/problem/primesnum

NOTE: I tested DMOJ pulling. It could pull from DMOJ based page.
Eg: https://oj.vnoi.info/problem/codetour24_f_g

**Comment by jmerle** [comment]
Fixed in 6b63fd487d0bc22511c6b9002a26b84e0b86a1c6, will be released within 24 hours. Thanks for reporting the issue!
