### ISSUE TITLE
Doesn't create file while SSH on VSCode

### ISSUE THREAD

**Issue by vuthanhtrung2010** [jmerle/competitive-companion#482]
So if I open a folder in local computer it will work.
But I have my workspace (Coder workspace) at https://workspace.trung.is-a.dev via terraform using docker coding Cpp tho. But the problem is after it parses problem. It doesn't prompt me or sth on VSCode if on SSH session. On localhost of my laptop it could pull tho.

The problem is it isnt local? I think it expose a port and recieve data post there. But the problem what if I am on SSH session?

**Comment by jmerle** [comment]
This sounds like an issue with a VS Code extension. Competitive Companion merely parses the problem pages and sends the data to `http://localhost:<port>/`, it is the responsibility of the tool that listens on one of Competitive Companion's ports to create files and/or open them. You should send this bug report to the developer(s) of the tool that you're using.
