### ISSUE TITLE
JetBrains IDE support

### ISSUE THREAD

**Issue by vuthanhtrung2010** [jmerle/competitive-companion#483]
Hi, I have using the ext for a while on VSCode. The problem is I could use IDE like CLion or PyCharm and I use AutoCP. I would like making competitive companion wider range with this suggestion.

Making in JetBrains IDE would better for competitive programmer who using JetBrains products. Make it easier to use and make competetive companion greater and more popularity!

**Comment by jmerle** [comment]
Competitive Companion only parses the problem pages and sends the extracted data to external tools. Those external tools are not made by me, nor is this the right place for issues regarding such tools.
