### ISSUE TITLE
VJudge contest parsing not working

### ISSUE THREAD

**Issue by bletelier** [jmerle/competitive-companion#484]
Hello!,

First, I wanna thanks for the great extension.

I'm testing the extension with the VJudge contests parse and it's not able to  parse the contest (in both active and ended contests). I ran the parser in the contest's overview page and in the contest's problems page, and both return the same error. If I click a problem and try to parse, the parser uses the VJudge problem parser without problems.

So, in both overview and problems contest (like this https://vjudge.net/contest/647442 https://vjudge.net/contest/647442#overview and https://vjudge.net/contest/647442#problem), the parser iterates the same number of problems that exists in the contests but each iteration runs into the following problem (for each task in the contest, in this case for tasks 1,2,3 and 4 since there are problems A,B,C and D)

![image](https://github.com/user-attachments/assets/4fa7bbb1-c854-4e71-bd3a-32ba3fdde62d)

Now if I click on problem A (https://vjudge.net/contest/647442#problem/A), the parser executes correctly parsing the single problem.

![image](https://github.com/user-attachments/assets/83687341-0f9f-4841-8ff8-936bd3ac06cc)

I assume it should be a bug, since the url in the GET method looks weird. 

If I'm doing something wrong please let me know. I hope this could be fixed since it's a really helpful extension!

**Comment by jmerle** [comment]
Fixed in baa27379908a178352499351f81d38fe84aadb2e, will be released within 24 hours. Thanks for reporting the issue!
