### ISSUE TITLE
about competitive companion default parser

### ISSUE THREAD

**Issue by f2666** [jmerle/competitive-companion#485]
when you use competitive companion to pull problem that on oiclass.com.  it will return "Competitive Companion could not determine which parser to parse this page with. Please right-click on the plus icon and select the parser to use via the "Parse with" context menu. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).". this OJ is in China,so if you can't connect to it,please use VPN.But when we click the icon and choose parser Hydro. it's OK , but it not in default parser ,when we choose Hydro,we can't use it to pull other OJ's Problem.

**Comment by f2666** [comment]
The exetension always choose the deflaut parser,not hydro. but default parser can't pull oiclass.com or other OJ that fork hydro.

**Comment by f2666** [comment]
this extension can't pull like this
![image](https://github.com/user-attachments/assets/9c7d2b92-0cb6-455b-b02e-60c5625e0898)
if we'd like to pull problem we must click like that
![image](https://github.com/user-attachments/assets/99c0343d-4165-4b36-aeed-feb7a13f547e)
![image](https://github.com/user-attachments/assets/627021b5-de58-41f3-b836-273410a04ba5)
it Very troublesome to pull problem in this site,

**Comment by qwedc001** [comment]
右键扩展->扩展选项->Custom rules里将oiclass.com设定为HydroParser即可解决此问题。
you can define custom rules by right clicking the plugin->options->custom rules and adding oiclass.com as HydroProblemParser

**Comment by jmerle** [comment]
Fixed in 92145330f3c6d9667157dee1c34569806cba48ba, will be released within 24 hours. Thanks for reporting the issue!

**Comment by f2666** [comment]
谢啦，要不然我还不会
________________________________
发件人: Eric Guo ***@***.***>
发送时间: 2024年9月16日 22:19
收件人: jmerle/competitive-companion ***@***.***>
抄送: f2666 ***@***.***>; Author ***@***.***>
主题: Re: [jmerle/competitive-companion] about competitive companion default parser (Issue #485)


右键扩展->扩展选项->Custom rules里将oiclass.com设定为HydroParser即可解决此问题。
you can define custom rules by right clicking the plugin->options->custom rules and adding oiclass.com as HydroProblemParser

―
