### ISSUE TITLE
pull wrong testcase

### ISSUE THREAD

**Issue by f2666** [jmerle/competitive-companion#486]
oiclass.com is a OJ that for [https://hydro.js.org/](url) , if some text are write in a code case this extension will pull it like test case.like this [https://oiclass.com/p/3683?tid=668ba5193b025cb5b4b6e3a6](url) 
![image](https://github.com/user-attachments/assets/d483b896-f39f-4687-a810-a2cd37985d32)
#485 and we must use hydro parser,or it can pull.

**Comment by qwedc001** [comment]
same issue here,hydro parser should judge whether the code-block begins with ```input and pull the case afterwards,maybe.

**Comment by jmerle** [comment]
I can't reach oiclass.com from my location, but based on the description of the issue e471ef73d88b92141adda27b7fc1107b497dda9b fixes it. Will be released within 24 hours.
