### ISSUE TITLE
Support Kattis Challenge (Problem) Parsing

### ISSUE THREAD

**Issue by Amazingkenneth** [jmerle/competitive-companion#489]
Page URL: https://open.kattis.com/challenge

Screenshot for reference:

![image](https://github.com/user-attachments/assets/214303a2-ce29-4f13-9fca-95cf5e6aff99)

**Comment by jmerle** [comment]
Fixed in 96a4cb537399abafad2aebc82497e7e73544ac44, will be released around Monday. Thanks for reporting the issue!
