### ISSUE TITLE
can't parse noip.ac problems

### ISSUE THREAD

**Issue by lierixia1** [jmerle/competitive-companion#499]
problem: https://noip.ac/rs/show_problem/1

**Comment by touhidurrr** [comment]
Most of the problems here does not even include a sample Input / Output. I wonder if support for this OJ will be helpful.

**Comment by touhidurrr** [comment]
Ok, after some thinking, I added support for it anyways. Even though most problems has no sample I/O, a lot of them do. It can be helpful for those problems.

**Comment by touhidurrr** [comment]
@lierixia1, the maintainers will close issues when they are resolved or GitHub automatically closes them when a linked pull request is merged. You should not close an issue yourself unless it has been resolved.
