### ISSUE TITLE
Consider supporting LightOJ

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#500]
Problem urls: either https://lightoj.com/problem/<problem_id> or https://lightoj.com/contest/<contest_id>/arena/problem/<problem_id>

Problem list in contest url: https://lightoj.com/contest/<contest_id>/arena/

Sample of problem html (from both contest and problemset) and problem list html is attached

[LightOJ.zip](https://github.com/user-attachments/files/17324863/LightOJ.zip)

**Comment by touhidurrr** [comment]
I tested some LightOJ problems and it already works fine from what I see. If a particular problem do not work then kindly mention its link.

**Comment by EgorKulikov** [comment]
Hm, I somehow missed it. It does not work for contests anyway (even if you select specific parser from parser list)

**Comment by touhidurrr** [comment]
I can try to implement it, but the problem is where are contests? I saw only one which I cannot enter.

**Comment by EgorKulikov** [comment]
> I can try to implement it, but the problem is where are contests? I saw only one which I cannot enter. For past contests I can only see the ranklist.

You can find sample pages in the zip I attached. You can also access them if you click "Past" on the left on the contest page

**Comment by touhidurrr** [comment]
Opened a pull request with the contest area support. Somewhat buggy but does what you want mostly.

**Comment by touhidurrr** [comment]
> You can find sample pages in the zip I attached. You can also access them if you click "Past" on the left on the contest page

Past contests, whether they are public or private, does not show a list of problems. Also, your zip is not adequate for testing. In the end, I had to open a test contest to test this.
