### ISSUE TITLE
`eslint` warning

### ISSUE THREAD

**Issue by touhidurrr** [jmerle/competitive-companion#504]
I am getting some warning running `eslint` for this project. It is telling me that the **TypeScript Eslint** plugin does not support the project TypeScript version.

Possible fixes:
1. Upgrade to `eslint@9`
2. Read **TypeScript Eslint** do use the plugin for the latest `eslint` version instead of the old one. (The package names are different)

**Comment by jmerle** [comment]
Although I've never had issues with newer TypeScript versions that don't yet have official TypeScript ESLint support, I've just downgraded TypeScript to the version range supported by TypeScript ESLint to resolve the warning.
