### ISSUE TITLE
 Hydro framework have recently started failing to parse

### ISSUE THREAD

**Issue by wood3** [jmerle/competitive-companion#508]
A lot of OJ using the Hydro framework have recently started failing to parse, presumably due to the addition of an embedded DOMAIN list?

For example, <https://oj.33dai.cn/p/D0036> get error: 

```
content.js:58  TypeError: Cannot read properties of undefined (reading '1')
    at _HydroProblemParser.parse (content.js:29:17855)
    at parse (content.js:58:12587)
    at content.js:58:13590
```

**Comment by jmerle** [comment]
I've added proper support for 33OJ (i.e. you'll no longer need to use the "Parse with" functionality or custom rules) in 0607c347d1baa8ad5259f89ed5cef1c145f4873b, which also fixes using the Hydro and DMOJ parsers on unsupported websites through the aforementioned "Parse with" functionality or custom rules. Will be released later this week, thanks for reporting the issue!
