### ISSUE TITLE
Some problems needing to preserve whitespaces

### ISSUE THREAD

**Issue by sam20908** [jmerle/competitive-companion#510]
Hello, I am the author of the VSCode plugin https://marketplace.visualstudio.com/items?itemName=sam20908.vscode-fastolympiccoding, which leverages your great plugin to gather test cases easily!

One of my users reported a misleading test case where they got a wrong answer on my extension because they followed the exact output format for the problem, yet both my extension and your plugin trim whitespace.

The problem: https://open.kattis.com/contests/w677ae/problems/glossaryarrangement

**Comment by jmerle** [comment]
![](https://github.com/user-attachments/assets/48a2e2b3-f504-4ffe-9e30-b80f3d62d39a)

The whitespace on Kaggle (left) and the whitespace in the testcases parsed by Competitive Companion (right) seem to match. Am I missing something?

**Comment by sam20908** [comment]
So sorry... turns out I had a hidden piece of code that does the trimming 🤦
