### ISSUE TITLE
Please support https://judge.eluminatis-of-lu.com/

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#513]

**Comment by jmerle** [comment]
Added in 1785dd19dba63666c86373947d99888ad2a68be4, will be released soon. SeriousOJ doesn't appear to consistently format sample cases the same way, so I've currently added support for the sample case formats in problems [1002](https://judge.eluminatis-of-lu.com/p/1002), [1003](https://judge.eluminatis-of-lu.com/p/1003), [1037](https://judge.eluminatis-of-lu.com/p/1037), and [1063](https://judge.eluminatis-of-lu.com/p/1063). Please open an issue if I missed another commonly used format.
