### ISSUE TITLE
Hi，could you add an OJ to parse

### ISSUE THREAD

**Issue by Ursphere** [jmerle/competitive-companion#523]
https://www.starrycoding.com/problem?pageNo=1&pageSize=20&title&difficulty=0

I would appreciate it if you can do it [rose]

**Comment by jmerle** [comment]
Added in 960ff116b392aef07712926a1ae87f1f7ddd9e71, will be released within 12 hours.

**Comment by Ursphere** [comment]
> Added in [960ff11](https://github.com/jmerle/competitive-companion/commit/960ff116b392aef07712926a1ae87f1f7ddd9e71), will be released within 12 hours.

Thank you very much.
