### ISSUE TITLE
Not working on a specific page

### ISSUE THREAD

**Issue by swadheen01** [jmerle/competitive-companion#524]
Its not working on a specific problem, i think it might be for a reason that this specific problem included some images into it. Or maybe some bugs. Here is the page link:
https://codeforces.net/contest/2047/problem/A
<img width="949" alt="Screenshot 2024-12-05 014311" src="https://github.com/user-attachments/assets/ef57cde9-93fc-4bfe-ba45-18d9fa799462">

**Comment by jmerle** [comment]
I didn't know the codeforces.net mirror of Codeforces, will add support for it within a few days. In the mean time, you can successfully parse the problem on codeforces.com: https://codeforces.net/contest/2047/problem/A

**Comment by jmerle** [comment]
Apologies for the delay, "within a few days" didn't quite work out. Anyways, fixed in e5f86aebd2d1d849d730c394933c09ccc4cf84b1, will be released before the end of 2024.
