### ISSUE TITLE
Parsing output as input in Kattis

### ISSUE THREAD

**Issue by shahriar374** [jmerle/competitive-companion#526]
Hi, The problem [Velkomin!](https://open.kattis.com/problems/velkomin), which doesn't have any input is parsed incorrectly. The extension is mistaking the output as input. 

<img width="500px" src="https://github.com/user-attachments/assets/59153d4f-3307-47e7-997f-0ce0bede84c5">

**Comment by jmerle** [comment]
Fixed in 08d9b9e48512b62409b08e29fb77fb1ab4cfe227, will be released within 24 hours. Thanks for reporting the issue!
