### ISSUE TITLE
Could not get the problem form lanqiao

### ISSUE THREAD

**Issue by Tsum0** [jmerle/competitive-companion#529]
I used the competitive-companion at edge
When I tried get problems from lanqiao, it sent a error message"Something went wrong while running Competitive Companion's LanqiaoProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page)."
URL:
https://www.lanqiao.cn/problems/504/learning/?page=1&first_category_id=1&sort=students_count&asc=0

**Comment by jmerle** [comment]
Fixed in 4cbb61d8c9819030bf4c7502f2c0ea97548ab226, will be released within 24 hours.
