### ISSUE TITLE
If two questions have the same name then it starts editing the previous file

### ISSUE THREAD

**Issue by Arpit-Raj1** [jmerle/competitive-companion#530]
if two questions have the same name, for example 
https://codeforces.com/contest/2041/problem/E and 
https://codeforces.com/contest/1986/problem/E

They both have the same name and then run it. It starts editing the previous problem. 
Maybe saving files with the contest number instead of just the question number will help, like E_Beautiful_Array.cpp will be saved as 2041E_Beautiful_Array will get it fixed.

**Comment by jmerle** [comment]
Competitive Companion only parses problem data and sends it to external tools. In other words, Competitive Companion isn't the one naming or opening the files on your local disk, and you should send this bug report to the developer(s) of the external tool you're using.
