### ISSUE TITLE
Add parser for Libre Online Judge

### ISSUE THREAD

**Issue by ouuan** [jmerle/competitive-companion#57]
URL: <https://loj.ac>

Sample problem: [「IOI2019」Arranging Shoes](https://loj.ac/problem/3175)

The sample tests are written in the `<pre></pre>` tags, I think it's usually safe to regard the first `<pre></pre>` tag as the first input, the second as the first output, the third as the second input…etc.

It will be better if only `<pre></pre>` in `<h4 class="ui top attached block header">样例</h4>` are considered.

Time limit: `<span class="ui label">时间限制：1000 ms</span>`

Memory limit: `<span class="ui label">内存限制：1024 MiB</span>`

**Comment by jmerle** [comment]
Implemented in 005aeab, will go live later today.
