### ISSUE TITLE
Add parser for Luogu Online Judge

### ISSUE THREAD

**Issue by ouuan** [jmerle/competitive-companion#58]
URL: <https://www.luogu.com.cn/>

Sample problem: [\[IOI2019\]Arranging Shoes](https://www.luogu.com.cn/problem/P5749)

Sample tests:

- `<div data-v-36768c72="" data-v-af321868="" class="sample-wrap sample" show-idx="true">`
   - `<div data-v-52f2d52f="" data-v-36768c72="" class="input">`
   - `<div data-v-52f2d52f="" data-v-36768c72="" class="output">`

Time limit: `<span data-v-83303c00="" class="value lfe-caption">1.00s</span>`

Memory limit: `<span data-v-83303c00="" class="value lfe-caption">125.00MB</span>`

**Comment by jmerle** [comment]
Implemented in 6aff544, will go live later today.
