### ISSUE TITLE
Add contest parser for LibreOJ and problem parser for problems in a contest

### ISSUE THREAD

**Issue by ouuan** [jmerle/competitive-companion#63]
Contest example: <https://loj.ac/contest/40>

Problem in contest example: <https://loj.ac/contest/40/problem/1> (This URL is not considered as a problem URL in the current version.)

**Comment by jmerle** [comment]
Implemented in 5ab57a6. Not sure when it goes live yet, see https://github.com/jmerle/competitive-companion/issues/62#issuecomment-570908834 for an explanation about that.

**Comment by jmerle** [comment]
This change has gone live in 2.11.0.
