### ISSUE TITLE
Add tool Competitive Programming Helper

### ISSUE THREAD

**Issue by agrawal-d** [jmerle/competitive-companion#65]
Please add the following tool to your release and readme.

Tool name : Competitive Programming Helper
VS Code store link:https://marketplace.visualstudio.com/items?itemName=DivyanshuAgrawal.competitive-programming-helper

Source Code: https://github.com/agrawal-d/competitive-programming-helper/tree/master

Port:`27121`

**Comment by jmerle** [comment]
Implemented in 9a4174e which will be released in about 6 hours.

**Comment by jmerle** [comment]
This change has gone live in 2.11.0.

**Comment by agrawal-d** [comment]
Thanks a lot! 🙂
