### ISSUE TITLE
Hackerrank does not parse

### ISSUE THREAD

**Issue by mafulafunk** [jmerle/competitive-companion#68]
Maybe a Layer 8 Problem.
I've got Chrome Extension installed.
And CHelper extension in Intellij.

The plugin parses from Codeforces like:
https://codeforces.com/problemset/problem/1307/G

but does not parse from Hackerrank, like:
https://www.hackerrank.com/challenges/simple-array-sum/problem

The CHacker extension behaves the same.

**Comment by jmerle** [comment]
I cannot reproduce this issue:
![](https://i.imgur.com/DMe81lV.png)

Can you try parsing the HackerRank problem with debug mode on and the console open to see if any errors appear? You can turn on debug mode by right-clicking on the plus icon, selecting "Options" and checking the checkbox in front of "Debug mode".

**Comment by mafulafunk** [comment]
Well.....what can I say, can't reproduce ist now either.
<img width="1063" alt="Screenshot 2020-02-19 at 22 53 03" src="https://user-images.githubusercontent.com/99756/74880023-b2d28000-536a-11ea-9663-65a2a15ec357.png">
Thank you for pointing me to the debug mode & sorry for the inconvenience.

**Comment by jmerle** [comment]
No worries, thanks for the quick reply! Feel free to create a new issue if you find a parser that causes an error in the console when parsing a problem/contest.
