### ISSUE TITLE
Support ssoier

### ISSUE THREAD

**Issue by testitem** [jmerle/competitive-companion#69]
Here's an example problem: [here](http://ybt.ssoier.cn:8088/problem_show.php?pid=1772)

<img width="923" alt="图片" src="https://user-images.githubusercontent.com/19212916/75856154-b405b180-5e2e-11ea-8021-0eb26a303248.png">

**Comment by testitem** [comment]
Also n i c e issue number

**Comment by jmerle** [comment]
Added in 271eacad16fea65d24b29b1fd8f791c5ce238eb8, will go live this weekend.
