### ISSUE TITLE
Unable to see the icon on my chrome toolbar

### ISSUE THREAD

**Issue by AJ-54** [jmerle/competitive-companion#72]
DevTools failed to parse SourceMap: chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/browser-polyfill.min.js.map
DevTools failed to parse SourceMap: chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/pdf.js.map

This is what console is showing 
Please help me.
There is also an error throwback on extension:
 "applications": {
      "gecko": {
         "id": "{74e326aa-c645-4495-9287-b6febc5565a7}"
      }
   },
says - 
1)Unrecognized manifest key 'applications'. and
2)Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

Note - It was working fine few days back .

**Comment by jmerle** [comment]
What operating system and what version of Chrome are you running? I cannot reproduce this locally.

**Comment by jmerle** [comment]
Closing this issue because there is no response. Feel free to create a new issue if you still get the same error.
