### ISSUE TITLE
Support Task parsing on mirrors

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [jmerle/competitive-companion#76]
Chinese users, due to bad internet connection, may choose codeforc.es or codeforces.ml as codeforces mirrors.

I am wondering if it is possible to add them to the supported list of judges.

**Comment by jmerle** [comment]
The codeforces.ml mirror was already added in 2.13.0, and I added the codeforc.es mirror in 2.14.0 which I just released. The Firefox version is already live, the Chrome version is currently pending review and should be available soon.
