### ISSUE TITLE
Google Codejam (2020 edition) not working.

### ISSUE THREAD

**Issue by mfornet** [jmerle/competitive-companion#77]
The parser for Google Codejam didn't work in the [Qualification Round this year (2020)](https://codingcompetitions.withgoogle.com/codejam/round/000000000019fd27). Maybe there were some changes in the platform, it would be very nice to have it for next rounds.

I tried to parse each problems separately, the icon was active on the problem page but on click it doesn't download testcases.

**Comment by jmerle** [comment]
I'm pretty sure it works fine since I used it myself last night. The only downside is that you have to refresh after opening a problem and before clicking the icon, although that will no longer be necessary once #74 is implemented. I'm planning to do that tomorrow.

**Comment by mfornet** [comment]
Ok, I tried and it works after refreshing, quite unfortunate though. Thanks.

**Comment by jmerle** [comment]
Fixed in 2.14.0 which I just released. The Firefox version is already live, the Chrome version is currently pending review and should be available soon.
