### ISSUE TITLE
Error in time limit analysis of Luogu problem

### ISSUE THREAD

**Issue by william-song-shy** [jmerle/competitive-companion#79]
Even if the time unit is milliseconds, the result of multiplying the value by 1000 will be returned.
[Example](https://www.luogu.com.cn/problem/U100521)

**Comment by jmerle** [comment]
Fixed in 2dff16455572e82bcfb0451a6947db8cfef63d2b. I will release it in a new version after 2.14.0 is approved by Google because I cannot upload any new versions to the Chrome Web Store until that has happened.
