### ISSUE TITLE
It is not working for codechef ?

### ISSUE THREAD

**Issue by rgkbitw** [jmerle/competitive-companion#8]
When  I'm on a codechef problem the marker changes to green and when I press it nothing happens.

**Comment by jmerle** [comment]
Can you share the link to the problem so I can try to reproduce the issue?

**Comment by rgkbitw** [comment]
https://www.codechef.com/LOCAPR18/problems/CRICSCR

https://www.codechef.com/KQ102018/problems/QM10B

It is supposed to work for all the problems right ?

**Comment by jmerle** [comment]
Yeah, you seem to be right. While I cannot make it parse the testcases for all problems (CodeChef does not have a standard format for all problems), it should not do nothing at all. Instead, it should extract what it can, and return an empty array of sample cases when it can't parse them successfully.

I will fix the issue in a few minutes.

**Comment by rgkbitw** [comment]
> CodeChef does not have a standard format for all problems

Okay, I was not aware of that. 

Thanks for being so prompt.

**Comment by jmerle** [comment]
Fixed in 2.2.2, it has been published to Chrome's Web Store and Mozilla's AMO, so it should be available within an hour. Depending on your browser, it might take between 5-24 hours before the extension is updated automatically (Chrome checks every 5 hours, Firefox once a day), but you can ofcourse always update manually.

**Comment by pranjalg131** [comment]
This is not working on live contests in codechef
namely
https://www.codechef.com/APRIL20B
https://www.codechef.com/LRNDSA02

**Comment by jmerle** [comment]
Thanks for the report @pranjalg131, fixed in 8c6134347f99e339d139c5185221758009c86b08 which will go live in the next release. In the future please create a new issue instead of replying on a nearly two years old one though.

**Comment by pranjalg131** [comment]
Ok I will keep that in mind next time
