### ISSUE TITLE
feature request : add Problem url as commented line in top of file

### ISSUE THREAD

**Issue by archie9211** [jmerle/competitive-companion#81]
it would be great if it can add the url of question for further convenience on the top of file.

**Comment by jmerle** [comment]
I don't understand what you mean. Are you requesting for data to be sent like this?

```json
https://codeforces.com/problemset/problem/954/G
{
    "name": "G. Castle Defense",
    "group": "Codeforces - Educational Codeforces Round 40 (Rated for Div. 2)",
    "url": "https://codeforces.com/problemset/problem/954/G",
    "interactive": false,
    "memoryLimit": 256,
    "timeLimit": 1500,
    "tests": [
        {
            "input": "5 0 6\n5 4 3 4 9\n",
            "output": "5\n"
        },
        {
            "input": "4 2 0\n1 2 3 4\n",
            "output": "6\n"
        },
        {
            "input": "5 1 1\n2 1 2 1 2\n",
            "output": "3\n"
        }
    ],
    "testType": "single",
    "input": {
        "type": "stdin"
    },
    "output": {
        "type": "stdout"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "GCastleDefense"
        }
    }
}
```

**Comment by archie9211** [comment]
yes, something like that.
When We click on the extension button it creates a file on vs code.

I want to append the url of problem in that file for future reference.. as commented like.


It should look like :

![ss](https://user-images.githubusercontent.com/25462010/78997231-c5e02000-7b63-11ea-83d2-c76afcad46dd.png)

**Comment by pranjalg131** [comment]
Yeah would love something like that so that it stays there for future reference

**Comment by jmerle** [comment]
> yes, something like that.
> When We click on the extension button it creates a file on vs code.
> 
> I want to append the url of problem in that file for future reference.. as commented like.
> 
> It should look like :
> 
> ![ss](https://user-images.githubusercontent.com/25462010/78997231-c5e02000-7b63-11ea-83d2-c76afcad46dd.png)

You'll have to request this feature from the developer of the VS Code extension you're using. Competitive Companion simply extracts the problem data and sends it to various tools, it does not control the content of the files created by those tools.

I am also not going to change the output of my extension as shown in my example, as that would break backwards-compatibility and because the URL is already embedded in the JSON object.
