### ISSUE TITLE
Keyboard Shortcut not Working

### ISSUE THREAD

**Issue by pranjalg131** [jmerle/competitive-companion#85]
Keyboard shortcut to parse tasks ie Ctrl + Shift + U is not working for version 2.15.1 but the extension can be used by clicking the button

**Comment by jmerle** [comment]
What browser are you using? If it is Chrome, could try going to `chrome://extensions/shortcuts` and manually editting the shortcut to `Ctrl + Shift + U` (even if it is already set to `Ctrl + Shift + U`? I was able to reproduce this issue, but after doing that it magically worked, even though it was already set to `Ctrl + Shift + U`.

**Comment by pranjalg131** [comment]
Got it Thanks
