### ISSUE TITLE
Parsing problems for HackerRank interview problems

### ISSUE THREAD

**Issue by lancehaoh** [jmerle/competitive-companion#9]
It seems that the tool is having issues detecting the input for the problems in the interview preparation kit in HackerRank. The button in my Chrome browser does not even light up for such problems.

Here is a link to one such [problem](https://www.hackerrank.com/challenges/minimum-swaps-2/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=arrays).

**Comment by jmerle** [comment]
Fixed in 9b1483b, will go live in a minute. Thanks for reporting the bug!
