### ISSUE TITLE
Add support with codeforces m1/m2/m3

### ISSUE THREAD

**Issue by tb148** [jmerle/competitive-companion#92]
Usually, when I am taking contests, I use m2.codeforces.com, but currently this project is not supporting m2, so I wish to add a feature for it!

**Comment by jmerle** [comment]
I'll see if I can get this implemented during round 639. Unfortunately the m1/m2/m3 subdomains only show problems during contests, so there is a limited timeframe in which this can be implemented which may cause it to take a bit longer.

**Comment by jmerle** [comment]
Fixed in 45fd23dd9af6bb9e1215d0f9e439f5f742d372f5, will be released either this weekend or somewhere next week.

**Comment by jmerle** [comment]
These changes have just been released in 2.16.0, which is already available on Firefox and will be available for Chrome users after Google has reviewed it.
