### ISSUE TITLE
.tcs file in different directory

### ISSUE THREAD

**Issue by aryan57** [jmerle/competitive-companion#96]
I use competitive companion along with competitive programming helper. Whenever I parse a question, it creates a .cpp and a .tcs in the same directory, which doesn't looks good. Is there a way in which only the .cpp files are created in the main directory and .tcs files somewhere else?

**Comment by jmerle** [comment]
Competitive Companion only parses problems and sends the extracted data to external tools like Competitive Programming Helper. Those external tools are not made by me, you should send this suggestion to the developer(s) of Competitive Programming Helper.
